// @flow
const AllOldWebsitePackages = [
  { "key":"analytics", "name":"Analytics", "ogAKRepo":true },
  { "key":"avatar", "name":"Avatar", "ogAKRepo":true },
  { "key":"badge","ogAKRepo":false, "name":"badge" }, 
  { "key":"banner", "name":"Banner", "ogAKRepo":true },
  { "key":"blanket", "name":"Blanket", "ogAKRepo":true },
  { "key":"breadcrumbs", "name":"Breadcrumbs", "ogAKRepo":true },
  { "key":"button-group", "name":"Button Group", "ogAKRepo":true },
  { "key":"button", "name":"Button", "ogAKRepo":true },
  { "key":"calendar","ogAKRepo":false, "name":"calendar" }, 
  { "key":"checkbox", "name":"Checkbox", "ogAKRepo":true },
  { "key":"comment", "name":"Comment", "ogAKRepo":true },
  { "key":"dropdown-menu", "name":"Dropdown Menu", "ogAKRepo":true },
  { "key":"dynamic-table", "name":"Dynamic Table", "ogAKRepo":true },
  { "key":"field-radio-group", "name":"Radio Group", "ogAKRepo":true },
  { "key":"field-range", "name":"Field Range", "ogAKRepo":true },
  { "key":"field-text-area", "name":"Text Field Area", "ogAKRepo":true },
  { "key":"field-text", "name":"Text Field", "ogAKRepo":true },
  { "key":"flag", "name":"Flag", "key":"flag", "ogAKRepo":true },
  { "key":"icon", "name":"Icon", "key":"icon", "ogAKRepo":true },
  { "key":"inline-dialog", "name":"Inline Dialog", "ogAKRepo":true },
  { "key":"inline-edit", "name":"Inline Edit", "ogAKRepo":true },
  { "key":"inline-message", "name":"Inline Message", "ogAKRepo":true },
  { "key":"layer-manager", "name":"Layer Manager", "ogAKRepo":true },
  { "key":"logo", "name":"Logo", "ogAKRepo":true },
  { "key":"lozenge","ogAKRepo":false, "name":"lozenge" }, 
  { "key":"modal-dialog", "name":"Modal Dialog", "ogAKRepo":true },
  { "key":"multi-select", "name":"Select (Multi)", "ogAKRepo":true },
  { "key":"navigation", "name":"Navigation", "ogAKRepo":true },
  { "key":"page-header", "name":"PageHeader", "ogAKRepo":true },
  { "key":"page", "name":"Page", "ogAKRepo":true },
  { "key":"pagination", "name":"Pagination", "ogAKRepo":true },
  { "key":"progress-indicator", "name":"Progress Indicator", "ogAKRepo" : true },
  { "key":"single-select", "name":"Select (Single)", "ogAKRepo":true },
  { "key":"spinner", "name":"Spinner", "ogAKRepo":true },
  { "key":"tabs", "name":"Tabs", "ogAKRepo":true },
  { "key":"tag-group","ogAKRepo":false, "name":"tag-group" }, 
  { "key":"tag","ogAKRepo":false, "name":"tag" }, 
  { "key":"theme", "name":"Theme", "ogAKRepo":true },
  { "key":"toggle", "name":"Toggle", "ogAKRepo":true },
  { "key":"tooltip", "name":"Tooltip", "ogAKRepo":true }
];

export default AllOldWebsitePackages
