// flow-typed signature: 7129c9e5e56b33422b84ae89050c0582
// flow-typed version: <<STUB>>/extract-react-types_v0.10.0/flow_v0.67.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'extract-react-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'extract-react-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'extract-react-types/flow-typed/npm/jest_v20.x.x' {
  declare module.exports: any;
}

declare module 'extract-react-types/kinds' {
  declare module.exports: any;
}

declare module 'extract-react-types/matchExported' {
  declare module.exports: any;
}

declare module 'extract-react-types/test' {
  declare module.exports: any;
}

declare module 'extract-react-types/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'extract-react-types/flow-typed/npm/jest_v20.x.x.js' {
  declare module.exports: $Exports<
    'extract-react-types/flow-typed/npm/jest_v20.x.x',
  >;
}
declare module 'extract-react-types/index' {
  declare module.exports: $Exports<'extract-react-types'>;
}
declare module 'extract-react-types/index.js' {
  declare module.exports: $Exports<'extract-react-types'>;
}
declare module 'extract-react-types/kinds.js' {
  declare module.exports: $Exports<'extract-react-types/kinds'>;
}
declare module 'extract-react-types/matchExported.js' {
  declare module.exports: $Exports<'extract-react-types/matchExported'>;
}
declare module 'extract-react-types/test.js' {
  declare module.exports: $Exports<'extract-react-types/test'>;
}
declare module 'extract-react-types/types.js' {
  declare module.exports: $Exports<'extract-react-types/types'>;
}
