export default {
  type: 'array',
  items: [
    [
      'paragraph',
      'bulletList',
      'mediaSingle',
      'orderedList',
      'heading',
      'panel',
      'blockquote',
      'rule',
      'codeBlock',
      'mediaGroup',
      'applicationCard',
      'decisionList',
      'taskList',
      'table',
      'extension',
      'bodiedExtension',
      'layoutSection_two_column',
      'layoutSection_three_column',
    ],
  ],
  minItems: 1,
};
