/* eslint-disable global-require */
/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify icon/build/createIconsDocs.js.
 * Add synonyms in icon/icons/synonyms.js.
 */

import Blog16Icon from '../glyph/blog/16';
import Branch16Icon from '../glyph/branch/16';
import Bug16Icon from '../glyph/bug/16';
import Calendar16Icon from '../glyph/calendar/16';
import Changes16Icon from '../glyph/changes/16';
import Code16Icon from '../glyph/code/16';
import Commit16Icon from '../glyph/commit/16';
import Epic16Icon from '../glyph/epic/16';
import Improvement16Icon from '../glyph/improvement/16';
import Incident16Icon from '../glyph/incident/16';
import Issue16Icon from '../glyph/issue/16';
import NewFeature16Icon from '../glyph/new-feature/16';
import Page16Icon from '../glyph/page/16';
import Problem16Icon from '../glyph/problem/16';
import PullRequest16Icon from '../glyph/pull-request/16';
import Question16Icon from '../glyph/question/16';
import Story16Icon from '../glyph/story/16';
import Subtask16Icon from '../glyph/subtask/16';
import Task16Icon from '../glyph/task/16';
import Blog24Icon from '../glyph/blog/24';
import Branch24Icon from '../glyph/branch/24';
import Bug24Icon from '../glyph/bug/24';
import Calendar24Icon from '../glyph/calendar/24';
import Changes24Icon from '../glyph/changes/24';
import Code24Icon from '../glyph/code/24';
import Commit24Icon from '../glyph/commit/24';
import Epic24Icon from '../glyph/epic/24';
import Improvement24Icon from '../glyph/improvement/24';
import Incident24Icon from '../glyph/incident/24';
import Issue24Icon from '../glyph/issue/24';
import NewFeature24Icon from '../glyph/new-feature/24';
import Page24Icon from '../glyph/page/24';
import Problem24Icon from '../glyph/problem/24';
import PullRequest24Icon from '../glyph/pull-request/24';
import Question24Icon from '../glyph/question/24';
import Story24Icon from '../glyph/story/24';
import Subtask24Icon from '../glyph/subtask/24';
import Task24Icon from '../glyph/task/24';

export default {
  'blog/16': {
    keywords: ['blog/16', 'blog16', 'object', 'icon-object'],
    component: Blog16Icon,
    componentName: 'Blog16Icon',
    package: '@atlaskit/icon-object/glyph/blog/16',
  },
  'branch/16': {
    keywords: ['branch/16', 'branch16', 'object', 'icon-object'],
    component: Branch16Icon,
    componentName: 'Branch16Icon',
    package: '@atlaskit/icon-object/glyph/branch/16',
  },
  'bug/16': {
    keywords: ['bug/16', 'bug16', 'object', 'icon-object'],
    component: Bug16Icon,
    componentName: 'Bug16Icon',
    package: '@atlaskit/icon-object/glyph/bug/16',
  },
  'calendar/16': {
    keywords: ['calendar/16', 'calendar16', 'object', 'icon-object'],
    component: Calendar16Icon,
    componentName: 'Calendar16Icon',
    package: '@atlaskit/icon-object/glyph/calendar/16',
  },
  'changes/16': {
    keywords: ['changes/16', 'changes16', 'object', 'icon-object'],
    component: Changes16Icon,
    componentName: 'Changes16Icon',
    package: '@atlaskit/icon-object/glyph/changes/16',
  },
  'code/16': {
    keywords: ['code/16', 'code16', 'object', 'icon-object'],
    component: Code16Icon,
    componentName: 'Code16Icon',
    package: '@atlaskit/icon-object/glyph/code/16',
  },
  'commit/16': {
    keywords: ['commit/16', 'commit16', 'object', 'icon-object'],
    component: Commit16Icon,
    componentName: 'Commit16Icon',
    package: '@atlaskit/icon-object/glyph/commit/16',
  },
  'epic/16': {
    keywords: ['epic/16', 'epic16', 'object', 'icon-object'],
    component: Epic16Icon,
    componentName: 'Epic16Icon',
    package: '@atlaskit/icon-object/glyph/epic/16',
  },
  'improvement/16': {
    keywords: ['improvement/16', 'improvement16', 'object', 'icon-object'],
    component: Improvement16Icon,
    componentName: 'Improvement16Icon',
    package: '@atlaskit/icon-object/glyph/improvement/16',
  },
  'incident/16': {
    keywords: ['incident/16', 'incident16', 'object', 'icon-object'],
    component: Incident16Icon,
    componentName: 'Incident16Icon',
    package: '@atlaskit/icon-object/glyph/incident/16',
  },
  'issue/16': {
    keywords: ['issue/16', 'issue16', 'object', 'icon-object'],
    component: Issue16Icon,
    componentName: 'Issue16Icon',
    package: '@atlaskit/icon-object/glyph/issue/16',
  },
  'new-feature/16': {
    keywords: ['new-feature/16', 'newfeature16', 'object', 'icon-object'],
    component: NewFeature16Icon,
    componentName: 'NewFeature16Icon',
    package: '@atlaskit/icon-object/glyph/new-feature/16',
  },
  'page/16': {
    keywords: ['page/16', 'page16', 'object', 'icon-object'],
    component: Page16Icon,
    componentName: 'Page16Icon',
    package: '@atlaskit/icon-object/glyph/page/16',
  },
  'problem/16': {
    keywords: ['problem/16', 'problem16', 'object', 'icon-object'],
    component: Problem16Icon,
    componentName: 'Problem16Icon',
    package: '@atlaskit/icon-object/glyph/problem/16',
  },
  'pull-request/16': {
    keywords: ['pull-request/16', 'pullrequest16', 'object', 'icon-object'],
    component: PullRequest16Icon,
    componentName: 'PullRequest16Icon',
    package: '@atlaskit/icon-object/glyph/pull-request/16',
  },
  'question/16': {
    keywords: ['question/16', 'question16', 'object', 'icon-object'],
    component: Question16Icon,
    componentName: 'Question16Icon',
    package: '@atlaskit/icon-object/glyph/question/16',
  },
  'story/16': {
    keywords: ['story/16', 'story16', 'object', 'icon-object'],
    component: Story16Icon,
    componentName: 'Story16Icon',
    package: '@atlaskit/icon-object/glyph/story/16',
  },
  'subtask/16': {
    keywords: ['subtask/16', 'subtask16', 'object', 'icon-object'],
    component: Subtask16Icon,
    componentName: 'Subtask16Icon',
    package: '@atlaskit/icon-object/glyph/subtask/16',
  },
  'task/16': {
    keywords: ['task/16', 'task16', 'object', 'icon-object'],
    component: Task16Icon,
    componentName: 'Task16Icon',
    package: '@atlaskit/icon-object/glyph/task/16',
  },
  'blog/24': {
    keywords: ['blog/24', 'blog24', 'object', 'icon-object'],
    component: Blog24Icon,
    componentName: 'Blog24Icon',
    package: '@atlaskit/icon-object/glyph/blog/24',
  },
  'branch/24': {
    keywords: ['branch/24', 'branch24', 'object', 'icon-object'],
    component: Branch24Icon,
    componentName: 'Branch24Icon',
    package: '@atlaskit/icon-object/glyph/branch/24',
  },
  'bug/24': {
    keywords: ['bug/24', 'bug24', 'object', 'icon-object'],
    component: Bug24Icon,
    componentName: 'Bug24Icon',
    package: '@atlaskit/icon-object/glyph/bug/24',
  },
  'calendar/24': {
    keywords: ['calendar/24', 'calendar24', 'object', 'icon-object'],
    component: Calendar24Icon,
    componentName: 'Calendar24Icon',
    package: '@atlaskit/icon-object/glyph/calendar/24',
  },
  'changes/24': {
    keywords: ['changes/24', 'changes24', 'object', 'icon-object'],
    component: Changes24Icon,
    componentName: 'Changes24Icon',
    package: '@atlaskit/icon-object/glyph/changes/24',
  },
  'code/24': {
    keywords: ['code/24', 'code24', 'object', 'icon-object'],
    component: Code24Icon,
    componentName: 'Code24Icon',
    package: '@atlaskit/icon-object/glyph/code/24',
  },
  'commit/24': {
    keywords: ['commit/24', 'commit24', 'object', 'icon-object'],
    component: Commit24Icon,
    componentName: 'Commit24Icon',
    package: '@atlaskit/icon-object/glyph/commit/24',
  },
  'epic/24': {
    keywords: ['epic/24', 'epic24', 'object', 'icon-object'],
    component: Epic24Icon,
    componentName: 'Epic24Icon',
    package: '@atlaskit/icon-object/glyph/epic/24',
  },
  'improvement/24': {
    keywords: ['improvement/24', 'improvement24', 'object', 'icon-object'],
    component: Improvement24Icon,
    componentName: 'Improvement24Icon',
    package: '@atlaskit/icon-object/glyph/improvement/24',
  },
  'incident/24': {
    keywords: ['incident/24', 'incident24', 'object', 'icon-object'],
    component: Incident24Icon,
    componentName: 'Incident24Icon',
    package: '@atlaskit/icon-object/glyph/incident/24',
  },
  'issue/24': {
    keywords: ['issue/24', 'issue24', 'object', 'icon-object'],
    component: Issue24Icon,
    componentName: 'Issue24Icon',
    package: '@atlaskit/icon-object/glyph/issue/24',
  },
  'new-feature/24': {
    keywords: ['new-feature/24', 'newfeature24', 'object', 'icon-object'],
    component: NewFeature24Icon,
    componentName: 'NewFeature24Icon',
    package: '@atlaskit/icon-object/glyph/new-feature/24',
  },
  'page/24': {
    keywords: ['page/24', 'page24', 'object', 'icon-object'],
    component: Page24Icon,
    componentName: 'Page24Icon',
    package: '@atlaskit/icon-object/glyph/page/24',
  },
  'problem/24': {
    keywords: ['problem/24', 'problem24', 'object', 'icon-object'],
    component: Problem24Icon,
    componentName: 'Problem24Icon',
    package: '@atlaskit/icon-object/glyph/problem/24',
  },
  'pull-request/24': {
    keywords: ['pull-request/24', 'pullrequest24', 'object', 'icon-object'],
    component: PullRequest24Icon,
    componentName: 'PullRequest24Icon',
    package: '@atlaskit/icon-object/glyph/pull-request/24',
  },
  'question/24': {
    keywords: ['question/24', 'question24', 'object', 'icon-object'],
    component: Question24Icon,
    componentName: 'Question24Icon',
    package: '@atlaskit/icon-object/glyph/question/24',
  },
  'story/24': {
    keywords: ['story/24', 'story24', 'object', 'icon-object'],
    component: Story24Icon,
    componentName: 'Story24Icon',
    package: '@atlaskit/icon-object/glyph/story/24',
  },
  'subtask/24': {
    keywords: ['subtask/24', 'subtask24', 'object', 'icon-object'],
    component: Subtask24Icon,
    componentName: 'Subtask24Icon',
    package: '@atlaskit/icon-object/glyph/subtask/24',
  },
  'task/24': {
    keywords: ['task/24', 'task24', 'object', 'icon-object'],
    component: Task24Icon,
    componentName: 'Task24Icon',
    package: '@atlaskit/icon-object/glyph/task/24',
  },
};
