export const templateTypes = [
  {
    title: 'Blog post',
    icon: 'Celebration',
    type: 'blog',
    info: 'Share news and announcements with your team',
  },
  {
    title: 'Meeting notes',
    icon: 'ClipboardList',
    type: 'blog',
    info: 'Share news and announcements with your team',
  },
  {
    title: 'Decision',
    icon: 'Experiment',
    type: 'retro',
    info: 'Share news and announcements with your team',
  },
  {
    title: 'Product Requirements',
    icon: 'Troubleshoot',
    type: 'retro',
    info: 'Share news and announcements with your team',
  },
  {
    title: 'Health Monitoring',
    icon: 'Health',
    type: 'health',
    info: 'Share news and announcements with your team',
  },
  {
    title: 'How to?',
    icon: 'Lightbulb',
    type: 'health',
    info: 'Share news and announcements with your team',
  },
  {
    title: 'Essay',
    icon: 'Memo',
    type: 'retro',
    info: 'Share news and announcements with your team',
  },
  {
    title: 'Q&A',
    icon: 'Q&A',
    type: 'retro',
    info: 'Share news and announcements with your team',
  },
  {
    title: 'Security Report',
    icon: 'Security',
    type: 'blog',
    info: 'Share security updates and announcements',
  },
  {
    title: 'Task Report',
    icon: 'TaskDone',
    type: 'health',
    info: 'Task progress updates',
  },
  {
    title: 'Statistics & Numbers',
    icon: 'Chart',
    type: 'retro',
    info: 'Visualise your data',
  },
  {
    title: 'Open Letter',
    icon: 'Letter',
    type: 'retro',
    info: 'Personalize your letters',
  },
  {
    title: 'Pie Chart',
    icon: 'PieChart',
    type: 'blog',
    info: 'See who grabs a bigger piece of pie',
  },
  {
    title: 'Problems & Risks',
    icon: 'Problem',
    type: 'health',
    info: 'State your problems and risks',
  },
  {
    title: 'Bug Reports',
    icon: 'Bug',
    type: 'retro',
    info: 'Finding bugs and fix it',
  },
  {
    title: 'Prediction and analysis',
    icon: 'Prediction',
    type: 'retro',
    info: 'Predict and analyse the future',
  },
];
