/* eslint-disable global-require */
/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify icon/build/createIconsDocs.js.
 * Add synonyms in icon/icons/synonyms.js.
 */

import Archive16Icon from '../glyph/archive/16';
import Audio16Icon from '../glyph/audio/16';
import Document16Icon from '../glyph/document/16';
import ExcelSpreadsheet16Icon from '../glyph/excel-spreadsheet/16';
import Executable16Icon from '../glyph/executable/16';
import Folder16Icon from '../glyph/folder/16';
import Generic16Icon from '../glyph/generic/16';
import Gif16Icon from '../glyph/gif/16';
import GoogleDoc16Icon from '../glyph/google-doc/16';
import GoogleForm16Icon from '../glyph/google-form/16';
import GoogleSheet16Icon from '../glyph/google-sheet/16';
import GoogleSlide16Icon from '../glyph/google-slide/16';
import Image16Icon from '../glyph/image/16';
import PdfDocument16Icon from '../glyph/pdf-document/16';
import PowerpointPresentation16Icon from '../glyph/powerpoint-presentation/16';
import Presentation16Icon from '../glyph/presentation/16';
import Sketch16Icon from '../glyph/sketch/16';
import SourceCode16Icon from '../glyph/source-code/16';
import Spreadsheet16Icon from '../glyph/spreadsheet/16';
import Video16Icon from '../glyph/video/16';
import WordDocument16Icon from '../glyph/word-document/16';
import Archive24Icon from '../glyph/archive/24';
import Audio24Icon from '../glyph/audio/24';
import Document24Icon from '../glyph/document/24';
import ExcelSpreadsheet24Icon from '../glyph/excel-spreadsheet/24';
import Executable24Icon from '../glyph/executable/24';
import Folder24Icon from '../glyph/folder/24';
import Generic24Icon from '../glyph/generic/24';
import Gif24Icon from '../glyph/gif/24';
import GoogleDoc24Icon from '../glyph/google-doc/24';
import GoogleForm24Icon from '../glyph/google-form/24';
import GoogleSheet24Icon from '../glyph/google-sheet/24';
import GoogleSlide24Icon from '../glyph/google-slide/24';
import Image24Icon from '../glyph/image/24';
import PdfDocument24Icon from '../glyph/pdf-document/24';
import PowerpointPresentation24Icon from '../glyph/powerpoint-presentation/24';
import Presentation24Icon from '../glyph/presentation/24';
import Sketch24Icon from '../glyph/sketch/24';
import SourceCode24Icon from '../glyph/source-code/24';
import Spreadsheet24Icon from '../glyph/spreadsheet/24';
import Video24Icon from '../glyph/video/24';
import WordDocument24Icon from '../glyph/word-document/24';
import Archive48Icon from '../glyph/archive/48';
import Audio48Icon from '../glyph/audio/48';
import Document48Icon from '../glyph/document/48';
import ExcelSpreadsheet48Icon from '../glyph/excel-spreadsheet/48';
import Executable48Icon from '../glyph/executable/48';
import Folder48Icon from '../glyph/folder/48';
import Generic48Icon from '../glyph/generic/48';
import Gif48Icon from '../glyph/gif/48';
import GoogleDoc48Icon from '../glyph/google-doc/48';
import GoogleForm48Icon from '../glyph/google-form/48';
import GoogleSheet48Icon from '../glyph/google-sheet/48';
import GoogleSlide48Icon from '../glyph/google-slide/48';
import Image48Icon from '../glyph/image/48';
import PdfDocument48Icon from '../glyph/pdf-document/48';
import PowerpointPresentation48Icon from '../glyph/powerpoint-presentation/48';
import Presentation48Icon from '../glyph/presentation/48';
import Sketch48Icon from '../glyph/sketch/48';
import SourceCode48Icon from '../glyph/source-code/48';
import Spreadsheet48Icon from '../glyph/spreadsheet/48';
import Video48Icon from '../glyph/video/48';
import WordDocument48Icon from '../glyph/word-document/48';

export default {
  'archive/16': {
    keywords: ['archive/16', 'archive16', 'file-type', 'icon-file-type'],
    component: Archive16Icon,
    componentName: 'Archive16Icon',
    package: '@atlaskit/icon-file-type/glyph/archive/16',
  },
  'audio/16': {
    keywords: ['audio/16', 'audio16', 'file-type', 'icon-file-type'],
    component: Audio16Icon,
    componentName: 'Audio16Icon',
    package: '@atlaskit/icon-file-type/glyph/audio/16',
  },
  'document/16': {
    keywords: ['document/16', 'document16', 'file-type', 'icon-file-type'],
    component: Document16Icon,
    componentName: 'Document16Icon',
    package: '@atlaskit/icon-file-type/glyph/document/16',
  },
  'excel-spreadsheet/16': {
    keywords: ['excel-spreadsheet/16', 'excelspreadsheet16', 'file-type', 'icon-file-type'],
    component: ExcelSpreadsheet16Icon,
    componentName: 'ExcelSpreadsheet16Icon',
    package: '@atlaskit/icon-file-type/glyph/excel-spreadsheet/16',
  },
  'executable/16': {
    keywords: ['executable/16', 'executable16', 'file-type', 'icon-file-type'],
    component: Executable16Icon,
    componentName: 'Executable16Icon',
    package: '@atlaskit/icon-file-type/glyph/executable/16',
  },
  'folder/16': {
    keywords: ['folder/16', 'folder16', 'file-type', 'icon-file-type'],
    component: Folder16Icon,
    componentName: 'Folder16Icon',
    package: '@atlaskit/icon-file-type/glyph/folder/16',
  },
  'generic/16': {
    keywords: ['generic/16', 'generic16', 'file-type', 'icon-file-type'],
    component: Generic16Icon,
    componentName: 'Generic16Icon',
    package: '@atlaskit/icon-file-type/glyph/generic/16',
  },
  'gif/16': {
    keywords: ['gif/16', 'gif16', 'file-type', 'icon-file-type'],
    component: Gif16Icon,
    componentName: 'Gif16Icon',
    package: '@atlaskit/icon-file-type/glyph/gif/16',
  },
  'google-doc/16': {
    keywords: ['google-doc/16', 'googledoc16', 'file-type', 'icon-file-type'],
    component: GoogleDoc16Icon,
    componentName: 'GoogleDoc16Icon',
    package: '@atlaskit/icon-file-type/glyph/google-doc/16',
  },
  'google-form/16': {
    keywords: ['google-form/16', 'googleform16', 'file-type', 'icon-file-type'],
    component: GoogleForm16Icon,
    componentName: 'GoogleForm16Icon',
    package: '@atlaskit/icon-file-type/glyph/google-form/16',
  },
  'google-sheet/16': {
    keywords: ['google-sheet/16', 'googlesheet16', 'file-type', 'icon-file-type'],
    component: GoogleSheet16Icon,
    componentName: 'GoogleSheet16Icon',
    package: '@atlaskit/icon-file-type/glyph/google-sheet/16',
  },
  'google-slide/16': {
    keywords: ['google-slide/16', 'googleslide16', 'file-type', 'icon-file-type'],
    component: GoogleSlide16Icon,
    componentName: 'GoogleSlide16Icon',
    package: '@atlaskit/icon-file-type/glyph/google-slide/16',
  },
  'image/16': {
    keywords: ['image/16', 'image16', 'file-type', 'icon-file-type'],
    component: Image16Icon,
    componentName: 'Image16Icon',
    package: '@atlaskit/icon-file-type/glyph/image/16',
  },
  'pdf-document/16': {
    keywords: ['pdf-document/16', 'pdfdocument16', 'file-type', 'icon-file-type'],
    component: PdfDocument16Icon,
    componentName: 'PdfDocument16Icon',
    package: '@atlaskit/icon-file-type/glyph/pdf-document/16',
  },
  'powerpoint-presentation/16': {
    keywords: ['powerpoint-presentation/16', 'powerpointpresentation16', 'file-type', 'icon-file-type'],
    component: PowerpointPresentation16Icon,
    componentName: 'PowerpointPresentation16Icon',
    package: '@atlaskit/icon-file-type/glyph/powerpoint-presentation/16',
  },
  'presentation/16': {
    keywords: ['presentation/16', 'presentation16', 'file-type', 'icon-file-type'],
    component: Presentation16Icon,
    componentName: 'Presentation16Icon',
    package: '@atlaskit/icon-file-type/glyph/presentation/16',
  },
  'sketch/16': {
    keywords: ['sketch/16', 'sketch16', 'file-type', 'icon-file-type'],
    component: Sketch16Icon,
    componentName: 'Sketch16Icon',
    package: '@atlaskit/icon-file-type/glyph/sketch/16',
  },
  'source-code/16': {
    keywords: ['source-code/16', 'sourcecode16', 'file-type', 'icon-file-type'],
    component: SourceCode16Icon,
    componentName: 'SourceCode16Icon',
    package: '@atlaskit/icon-file-type/glyph/source-code/16',
  },
  'spreadsheet/16': {
    keywords: ['spreadsheet/16', 'spreadsheet16', 'file-type', 'icon-file-type'],
    component: Spreadsheet16Icon,
    componentName: 'Spreadsheet16Icon',
    package: '@atlaskit/icon-file-type/glyph/spreadsheet/16',
  },
  'video/16': {
    keywords: ['video/16', 'video16', 'file-type', 'icon-file-type'],
    component: Video16Icon,
    componentName: 'Video16Icon',
    package: '@atlaskit/icon-file-type/glyph/video/16',
  },
  'word-document/16': {
    keywords: ['word-document/16', 'worddocument16', 'file-type', 'icon-file-type'],
    component: WordDocument16Icon,
    componentName: 'WordDocument16Icon',
    package: '@atlaskit/icon-file-type/glyph/word-document/16',
  },
  'archive/24': {
    keywords: ['archive/24', 'archive24', 'file-type', 'icon-file-type'],
    component: Archive24Icon,
    componentName: 'Archive24Icon',
    package: '@atlaskit/icon-file-type/glyph/archive/24',
  },
  'audio/24': {
    keywords: ['audio/24', 'audio24', 'file-type', 'icon-file-type'],
    component: Audio24Icon,
    componentName: 'Audio24Icon',
    package: '@atlaskit/icon-file-type/glyph/audio/24',
  },
  'document/24': {
    keywords: ['document/24', 'document24', 'file-type', 'icon-file-type'],
    component: Document24Icon,
    componentName: 'Document24Icon',
    package: '@atlaskit/icon-file-type/glyph/document/24',
  },
  'excel-spreadsheet/24': {
    keywords: ['excel-spreadsheet/24', 'excelspreadsheet24', 'file-type', 'icon-file-type'],
    component: ExcelSpreadsheet24Icon,
    componentName: 'ExcelSpreadsheet24Icon',
    package: '@atlaskit/icon-file-type/glyph/excel-spreadsheet/24',
  },
  'executable/24': {
    keywords: ['executable/24', 'executable24', 'file-type', 'icon-file-type'],
    component: Executable24Icon,
    componentName: 'Executable24Icon',
    package: '@atlaskit/icon-file-type/glyph/executable/24',
  },
  'folder/24': {
    keywords: ['folder/24', 'folder24', 'file-type', 'icon-file-type'],
    component: Folder24Icon,
    componentName: 'Folder24Icon',
    package: '@atlaskit/icon-file-type/glyph/folder/24',
  },
  'generic/24': {
    keywords: ['generic/24', 'generic24', 'file-type', 'icon-file-type'],
    component: Generic24Icon,
    componentName: 'Generic24Icon',
    package: '@atlaskit/icon-file-type/glyph/generic/24',
  },
  'gif/24': {
    keywords: ['gif/24', 'gif24', 'file-type', 'icon-file-type'],
    component: Gif24Icon,
    componentName: 'Gif24Icon',
    package: '@atlaskit/icon-file-type/glyph/gif/24',
  },
  'google-doc/24': {
    keywords: ['google-doc/24', 'googledoc24', 'file-type', 'icon-file-type'],
    component: GoogleDoc24Icon,
    componentName: 'GoogleDoc24Icon',
    package: '@atlaskit/icon-file-type/glyph/google-doc/24',
  },
  'google-form/24': {
    keywords: ['google-form/24', 'googleform24', 'file-type', 'icon-file-type'],
    component: GoogleForm24Icon,
    componentName: 'GoogleForm24Icon',
    package: '@atlaskit/icon-file-type/glyph/google-form/24',
  },
  'google-sheet/24': {
    keywords: ['google-sheet/24', 'googlesheet24', 'file-type', 'icon-file-type'],
    component: GoogleSheet24Icon,
    componentName: 'GoogleSheet24Icon',
    package: '@atlaskit/icon-file-type/glyph/google-sheet/24',
  },
  'google-slide/24': {
    keywords: ['google-slide/24', 'googleslide24', 'file-type', 'icon-file-type'],
    component: GoogleSlide24Icon,
    componentName: 'GoogleSlide24Icon',
    package: '@atlaskit/icon-file-type/glyph/google-slide/24',
  },
  'image/24': {
    keywords: ['image/24', 'image24', 'file-type', 'icon-file-type'],
    component: Image24Icon,
    componentName: 'Image24Icon',
    package: '@atlaskit/icon-file-type/glyph/image/24',
  },
  'pdf-document/24': {
    keywords: ['pdf-document/24', 'pdfdocument24', 'file-type', 'icon-file-type'],
    component: PdfDocument24Icon,
    componentName: 'PdfDocument24Icon',
    package: '@atlaskit/icon-file-type/glyph/pdf-document/24',
  },
  'powerpoint-presentation/24': {
    keywords: ['powerpoint-presentation/24', 'powerpointpresentation24', 'file-type', 'icon-file-type'],
    component: PowerpointPresentation24Icon,
    componentName: 'PowerpointPresentation24Icon',
    package: '@atlaskit/icon-file-type/glyph/powerpoint-presentation/24',
  },
  'presentation/24': {
    keywords: ['presentation/24', 'presentation24', 'file-type', 'icon-file-type'],
    component: Presentation24Icon,
    componentName: 'Presentation24Icon',
    package: '@atlaskit/icon-file-type/glyph/presentation/24',
  },
  'sketch/24': {
    keywords: ['sketch/24', 'sketch24', 'file-type', 'icon-file-type'],
    component: Sketch24Icon,
    componentName: 'Sketch24Icon',
    package: '@atlaskit/icon-file-type/glyph/sketch/24',
  },
  'source-code/24': {
    keywords: ['source-code/24', 'sourcecode24', 'file-type', 'icon-file-type'],
    component: SourceCode24Icon,
    componentName: 'SourceCode24Icon',
    package: '@atlaskit/icon-file-type/glyph/source-code/24',
  },
  'spreadsheet/24': {
    keywords: ['spreadsheet/24', 'spreadsheet24', 'file-type', 'icon-file-type'],
    component: Spreadsheet24Icon,
    componentName: 'Spreadsheet24Icon',
    package: '@atlaskit/icon-file-type/glyph/spreadsheet/24',
  },
  'video/24': {
    keywords: ['video/24', 'video24', 'file-type', 'icon-file-type'],
    component: Video24Icon,
    componentName: 'Video24Icon',
    package: '@atlaskit/icon-file-type/glyph/video/24',
  },
  'word-document/24': {
    keywords: ['word-document/24', 'worddocument24', 'file-type', 'icon-file-type'],
    component: WordDocument24Icon,
    componentName: 'WordDocument24Icon',
    package: '@atlaskit/icon-file-type/glyph/word-document/24',
  },
  'archive/48': {
    keywords: ['archive/48', 'archive48', 'file-type', 'icon-file-type'],
    component: Archive48Icon,
    componentName: 'Archive48Icon',
    package: '@atlaskit/icon-file-type/glyph/archive/48',
  },
  'audio/48': {
    keywords: ['audio/48', 'audio48', 'file-type', 'icon-file-type'],
    component: Audio48Icon,
    componentName: 'Audio48Icon',
    package: '@atlaskit/icon-file-type/glyph/audio/48',
  },
  'document/48': {
    keywords: ['document/48', 'document48', 'file-type', 'icon-file-type'],
    component: Document48Icon,
    componentName: 'Document48Icon',
    package: '@atlaskit/icon-file-type/glyph/document/48',
  },
  'excel-spreadsheet/48': {
    keywords: ['excel-spreadsheet/48', 'excelspreadsheet48', 'file-type', 'icon-file-type'],
    component: ExcelSpreadsheet48Icon,
    componentName: 'ExcelSpreadsheet48Icon',
    package: '@atlaskit/icon-file-type/glyph/excel-spreadsheet/48',
  },
  'executable/48': {
    keywords: ['executable/48', 'executable48', 'file-type', 'icon-file-type'],
    component: Executable48Icon,
    componentName: 'Executable48Icon',
    package: '@atlaskit/icon-file-type/glyph/executable/48',
  },
  'folder/48': {
    keywords: ['folder/48', 'folder48', 'file-type', 'icon-file-type'],
    component: Folder48Icon,
    componentName: 'Folder48Icon',
    package: '@atlaskit/icon-file-type/glyph/folder/48',
  },
  'generic/48': {
    keywords: ['generic/48', 'generic48', 'file-type', 'icon-file-type'],
    component: Generic48Icon,
    componentName: 'Generic48Icon',
    package: '@atlaskit/icon-file-type/glyph/generic/48',
  },
  'gif/48': {
    keywords: ['gif/48', 'gif48', 'file-type', 'icon-file-type'],
    component: Gif48Icon,
    componentName: 'Gif48Icon',
    package: '@atlaskit/icon-file-type/glyph/gif/48',
  },
  'google-doc/48': {
    keywords: ['google-doc/48', 'googledoc48', 'file-type', 'icon-file-type'],
    component: GoogleDoc48Icon,
    componentName: 'GoogleDoc48Icon',
    package: '@atlaskit/icon-file-type/glyph/google-doc/48',
  },
  'google-form/48': {
    keywords: ['google-form/48', 'googleform48', 'file-type', 'icon-file-type'],
    component: GoogleForm48Icon,
    componentName: 'GoogleForm48Icon',
    package: '@atlaskit/icon-file-type/glyph/google-form/48',
  },
  'google-sheet/48': {
    keywords: ['google-sheet/48', 'googlesheet48', 'file-type', 'icon-file-type'],
    component: GoogleSheet48Icon,
    componentName: 'GoogleSheet48Icon',
    package: '@atlaskit/icon-file-type/glyph/google-sheet/48',
  },
  'google-slide/48': {
    keywords: ['google-slide/48', 'googleslide48', 'file-type', 'icon-file-type'],
    component: GoogleSlide48Icon,
    componentName: 'GoogleSlide48Icon',
    package: '@atlaskit/icon-file-type/glyph/google-slide/48',
  },
  'image/48': {
    keywords: ['image/48', 'image48', 'file-type', 'icon-file-type'],
    component: Image48Icon,
    componentName: 'Image48Icon',
    package: '@atlaskit/icon-file-type/glyph/image/48',
  },
  'pdf-document/48': {
    keywords: ['pdf-document/48', 'pdfdocument48', 'file-type', 'icon-file-type'],
    component: PdfDocument48Icon,
    componentName: 'PdfDocument48Icon',
    package: '@atlaskit/icon-file-type/glyph/pdf-document/48',
  },
  'powerpoint-presentation/48': {
    keywords: ['powerpoint-presentation/48', 'powerpointpresentation48', 'file-type', 'icon-file-type'],
    component: PowerpointPresentation48Icon,
    componentName: 'PowerpointPresentation48Icon',
    package: '@atlaskit/icon-file-type/glyph/powerpoint-presentation/48',
  },
  'presentation/48': {
    keywords: ['presentation/48', 'presentation48', 'file-type', 'icon-file-type'],
    component: Presentation48Icon,
    componentName: 'Presentation48Icon',
    package: '@atlaskit/icon-file-type/glyph/presentation/48',
  },
  'sketch/48': {
    keywords: ['sketch/48', 'sketch48', 'file-type', 'icon-file-type'],
    component: Sketch48Icon,
    componentName: 'Sketch48Icon',
    package: '@atlaskit/icon-file-type/glyph/sketch/48',
  },
  'source-code/48': {
    keywords: ['source-code/48', 'sourcecode48', 'file-type', 'icon-file-type'],
    component: SourceCode48Icon,
    componentName: 'SourceCode48Icon',
    package: '@atlaskit/icon-file-type/glyph/source-code/48',
  },
  'spreadsheet/48': {
    keywords: ['spreadsheet/48', 'spreadsheet48', 'file-type', 'icon-file-type'],
    component: Spreadsheet48Icon,
    componentName: 'Spreadsheet48Icon',
    package: '@atlaskit/icon-file-type/glyph/spreadsheet/48',
  },
  'video/48': {
    keywords: ['video/48', 'video48', 'file-type', 'icon-file-type'],
    component: Video48Icon,
    componentName: 'Video48Icon',
    package: '@atlaskit/icon-file-type/glyph/video/48',
  },
  'word-document/48': {
    keywords: ['word-document/48', 'worddocument48', 'file-type', 'icon-file-type'],
    component: WordDocument48Icon,
    componentName: 'WordDocument48Icon',
    package: '@atlaskit/icon-file-type/glyph/word-document/48',
  },
};
