/* eslint-disable global-require */
/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify icon/build/createIconsDocs.js.
 * Add synonyms in icon/icons/synonyms.js.
 */

import ActivityIcon from '../glyph/activity';
import AddCircleIcon from '../glyph/add-circle';
import AddItemIcon from '../glyph/add-item';
import AddIcon from '../glyph/add';
import AddonIcon from '../glyph/addon';
import AppAccessIcon from '../glyph/app-access';
import AppSwitcherIcon from '../glyph/app-switcher';
import ArrowDownCircleIcon from '../glyph/arrow-down-circle';
import ArrowDownIcon from '../glyph/arrow-down';
import ArrowLeftCircleIcon from '../glyph/arrow-left-circle';
import ArrowLeftIcon from '../glyph/arrow-left';
import ArrowRightCircleIcon from '../glyph/arrow-right-circle';
import ArrowRightIcon from '../glyph/arrow-right';
import ArrowUpCircleIcon from '../glyph/arrow-up-circle';
import ArrowUpIcon from '../glyph/arrow-up';
import AttachmentIcon from '../glyph/attachment';
import AudioCircleIcon from '../glyph/audio-circle';
import AudioIcon from '../glyph/audio';
import BacklogIcon from '../glyph/backlog';
import BillingFilledIcon from '../glyph/billing-filled';
import BillingIcon from '../glyph/billing';
import BitbucketBranchesIcon from '../glyph/bitbucket/branches';
import BitbucketBuildsIcon from '../glyph/bitbucket/builds';
import BitbucketCloneIcon from '../glyph/bitbucket/clone';
import BitbucketCommitsIcon from '../glyph/bitbucket/commits';
import BitbucketCompareIcon from '../glyph/bitbucket/compare';
import BitbucketForksIcon from '../glyph/bitbucket/forks';
import BitbucketOutputIcon from '../glyph/bitbucket/output';
import BitbucketPipelinesIcon from '../glyph/bitbucket/pipelines';
import BitbucketPullrequestsIcon from '../glyph/bitbucket/pullrequests';
import BitbucketReposIcon from '../glyph/bitbucket/repos';
import BitbucketSnippetsIcon from '../glyph/bitbucket/snippets';
import BitbucketSourceIcon from '../glyph/bitbucket/source';
import BoardIcon from '../glyph/board';
import BookIcon from '../glyph/book';
import BulletListIcon from '../glyph/bullet-list';
import CalendarFilledIcon from '../glyph/calendar-filled';
import CalendarIcon from '../glyph/calendar';
import CameraFilledIcon from '../glyph/camera-filled';
import CameraRotateIcon from '../glyph/camera-rotate';
import CameraTakePictureIcon from '../glyph/camera-take-picture';
import CameraIcon from '../glyph/camera';
import CanvasIcon from '../glyph/canvas';
import CheckCircleOutlineIcon from '../glyph/check-circle-outline';
import CheckCircleIcon from '../glyph/check-circle';
import CheckIcon from '../glyph/check';
import CheckboxIndeterminateIcon from '../glyph/checkbox-indeterminate';
import CheckboxIcon from '../glyph/checkbox';
import ChevronDownCircleIcon from '../glyph/chevron-down-circle';
import ChevronDownIcon from '../glyph/chevron-down';
import ChevronLeftCircleIcon from '../glyph/chevron-left-circle';
import ChevronLeftLargeIcon from '../glyph/chevron-left-large';
import ChevronLeftIcon from '../glyph/chevron-left';
import ChevronRightCircleIcon from '../glyph/chevron-right-circle';
import ChevronRightLargeIcon from '../glyph/chevron-right-large';
import ChevronRightIcon from '../glyph/chevron-right';
import ChevronUpCircleIcon from '../glyph/chevron-up-circle';
import ChevronUpIcon from '../glyph/chevron-up';
import ChildIssuesIcon from '../glyph/child-issues';
import CodeIcon from '../glyph/code';
import CommentIcon from '../glyph/comment';
import ComponentIcon from '../glyph/component';
import CopyIcon from '../glyph/copy';
import CreditcardFilledIcon from '../glyph/creditcard-filled';
import CreditcardIcon from '../glyph/creditcard';
import CrossCircleIcon from '../glyph/cross-circle';
import CrossIcon from '../glyph/cross';
import DashboardIcon from '../glyph/dashboard';
import DecisionIcon from '../glyph/decision';
import DepartmentIcon from '../glyph/department';
import DetailViewIcon from '../glyph/detail-view';
import DiscoverFilledIcon from '../glyph/discover-filled';
import DiscoverIcon from '../glyph/discover';
import DocumentFilledIcon from '../glyph/document-filled';
import DocumentIcon from '../glyph/document';
import DocumentsIcon from '../glyph/documents';
import DownloadIcon from '../glyph/download';
import DragHandlerIcon from '../glyph/drag-handler';
import DropboxIcon from '../glyph/dropbox';
import EditFilledIcon from '../glyph/edit-filled';
import EditIcon from '../glyph/edit';
import EditorAddIcon from '../glyph/editor/add';
import EditorAddonIcon from '../glyph/editor/addon';
import EditorAdvancedIcon from '../glyph/editor/advanced';
import EditorAlignCenterIcon from '../glyph/editor/align-center';
import EditorAlignImageCenterIcon from '../glyph/editor/align-image-center';
import EditorAlignImageLeftIcon from '../glyph/editor/align-image-left';
import EditorAlignImageRightIcon from '../glyph/editor/align-image-right';
import EditorAlignLeftIcon from '../glyph/editor/align-left';
import EditorAlignRightIcon from '../glyph/editor/align-right';
import EditorAttachmentIcon from '../glyph/editor/attachment';
import EditorBackgroundColorIcon from '../glyph/editor/background-color';
import EditorBoldIcon from '../glyph/editor/bold';
import EditorBulletListIcon from '../glyph/editor/bullet-list';
import EditorCloseIcon from '../glyph/editor/close';
import EditorCodeIcon from '../glyph/editor/code';
import EditorCollapseIcon from '../glyph/editor/collapse';
import EditorDateIcon from '../glyph/editor/date';
import EditorDecisionIcon from '../glyph/editor/decision';
import EditorDividerIcon from '../glyph/editor/divider';
import EditorDoneIcon from '../glyph/editor/done';
import EditorEditIcon from '../glyph/editor/edit';
import EditorEmojiIcon from '../glyph/editor/emoji';
import EditorErrorIcon from '../glyph/editor/error';
import EditorExpandIcon from '../glyph/editor/expand';
import EditorFeedbackIcon from '../glyph/editor/feedback';
import EditorFileIcon from '../glyph/editor/file';
import EditorHelpIcon from '../glyph/editor/help';
import EditorHintIcon from '../glyph/editor/hint';
import EditorHorizontalRuleIcon from '../glyph/editor/horizontal-rule';
import EditorImageBorderIcon from '../glyph/editor/image-border';
import EditorImageResizeIcon from '../glyph/editor/image-resize';
import EditorImageIcon from '../glyph/editor/image';
import EditorIndentIcon from '../glyph/editor/indent';
import EditorInfoIcon from '../glyph/editor/info';
import EditorItalicIcon from '../glyph/editor/italic';
import EditorLayoutThreeEqualIcon from '../glyph/editor/layout-three-equal';
import EditorLayoutThreeWithSidebarsIcon from '../glyph/editor/layout-three-with-sidebars';
import EditorLayoutTwoEqualIcon from '../glyph/editor/layout-two-equal';
import EditorLayoutTwoLeftSidebarIcon from '../glyph/editor/layout-two-left-sidebar';
import EditorLayoutTwoRightSidebarIcon from '../glyph/editor/layout-two-right-sidebar';
import EditorLinkIcon from '../glyph/editor/link';
import EditorMediaCenterIcon from '../glyph/editor/media-center';
import EditorMediaFullWidthIcon from '../glyph/editor/media-full-width';
import EditorMediaWideIcon from '../glyph/editor/media-wide';
import EditorMediaWrapLeftIcon from '../glyph/editor/media-wrap-left';
import EditorMediaWrapRightIcon from '../glyph/editor/media-wrap-right';
import EditorMentionIcon from '../glyph/editor/mention';
import EditorMoreIcon from '../glyph/editor/more';
import EditorNoteIcon from '../glyph/editor/note';
import EditorNumberListIcon from '../glyph/editor/number-list';
import EditorOpenIcon from '../glyph/editor/open';
import EditorOutdentIcon from '../glyph/editor/outdent';
import EditorPanelIcon from '../glyph/editor/panel';
import EditorPhotoIcon from '../glyph/editor/photo';
import EditorQuoteIcon from '../glyph/editor/quote';
import EditorRecentIcon from '../glyph/editor/recent';
import EditorRedoIcon from '../glyph/editor/redo';
import EditorRemoveIcon from '../glyph/editor/remove';
import EditorSearchIcon from '../glyph/editor/search';
import EditorSettingsIcon from '../glyph/editor/settings';
import EditorStrikethroughIcon from '../glyph/editor/strikethrough';
import EditorSuccessIcon from '../glyph/editor/success';
import EditorTableDisplayOptionsIcon from '../glyph/editor/table-display-options';
import EditorTableIcon from '../glyph/editor/table';
import EditorTaskIcon from '../glyph/editor/task';
import EditorTextColorIcon from '../glyph/editor/text-color';
import EditorTextStyleIcon from '../glyph/editor/text-style';
import EditorUnderlineIcon from '../glyph/editor/underline';
import EditorUndoIcon from '../glyph/editor/undo';
import EditorUnlinkIcon from '../glyph/editor/unlink';
import EditorWarningIcon from '../glyph/editor/warning';
import EmailIcon from '../glyph/email';
import EmojiAddIcon from '../glyph/emoji-add';
import EmojiIcon from '../glyph/emoji';
import EmojiActivityIcon from '../glyph/emoji/activity';
import EmojiAtlassianIcon from '../glyph/emoji/atlassian';
import EmojiCustomIcon from '../glyph/emoji/custom';
import EmojiEmojiIcon from '../glyph/emoji/emoji';
import EmojiFlagsIcon from '../glyph/emoji/flags';
import EmojiFoodIcon from '../glyph/emoji/food';
import EmojiFrequentIcon from '../glyph/emoji/frequent';
import EmojiKeyboardIcon from '../glyph/emoji/keyboard';
import EmojiNatureIcon from '../glyph/emoji/nature';
import EmojiObjectsIcon from '../glyph/emoji/objects';
import EmojiPeopleIcon from '../glyph/emoji/people';
import EmojiProductivityIcon from '../glyph/emoji/productivity';
import EmojiSymbolsIcon from '../glyph/emoji/symbols';
import EmojiTravelIcon from '../glyph/emoji/travel';
import ErrorIcon from '../glyph/error';
import ExportIcon from '../glyph/export';
import FeedbackIcon from '../glyph/feedback';
import FileIcon from '../glyph/file';
import FilterIcon from '../glyph/filter';
import FlagFilledIcon from '../glyph/flag-filled';
import FolderFilledIcon from '../glyph/folder-filled';
import FolderIcon from '../glyph/folder';
import FollowersIcon from '../glyph/followers';
import FollowingIcon from '../glyph/following';
import GoogledriveIcon from '../glyph/googledrive';
import GraphBarIcon from '../glyph/graph-bar';
import GraphLineIcon from '../glyph/graph-line';
import GsuiteIcon from '../glyph/gsuite';
import HighlightsIcon from '../glyph/highlights';
import HipchatAudioOnlyIcon from '../glyph/hipchat/audio-only';
import HipchatChevronDoubleDownIcon from '../glyph/hipchat/chevron-double-down';
import HipchatChevronDoubleUpIcon from '../glyph/hipchat/chevron-double-up';
import HipchatChevronDownIcon from '../glyph/hipchat/chevron-down';
import HipchatChevronUpIcon from '../glyph/hipchat/chevron-up';
import HipchatDialOutIcon from '../glyph/hipchat/dial-out';
import HipchatLobbyIcon from '../glyph/hipchat/lobby';
import HipchatMediaAttachmentCountIcon from '../glyph/hipchat/media-attachment-count';
import HipchatOutgoingSoundIcon from '../glyph/hipchat/outgoing-sound';
import HipchatSdVideoIcon from '../glyph/hipchat/sd-video';
import HomeCircleIcon from '../glyph/home-circle';
import HomeFilledIcon from '../glyph/home-filled';
import ImageBorderIcon from '../glyph/image-border';
import ImageResizeIcon from '../glyph/image-resize';
import ImageIcon from '../glyph/image';
import InfoIcon from '../glyph/info';
import InviteTeamIcon from '../glyph/invite-team';
import IssueRaiseIcon from '../glyph/issue-raise';
import IssueIcon from '../glyph/issue';
import IssuesIcon from '../glyph/issues';
import JiraBlockerIcon from '../glyph/jira/blocker';
import JiraCaptureIcon from '../glyph/jira/capture';
import JiraCriticalIcon from '../glyph/jira/critical';
import JiraFailedBuildStatusIcon from '../glyph/jira/failed-build-status';
import JiraLabsIcon from '../glyph/jira/labs';
import JiraMajorIcon from '../glyph/jira/major';
import JiraMediumIcon from '../glyph/jira/medium';
import JiraMinorIcon from '../glyph/jira/minor';
import JiraTestSessionIcon from '../glyph/jira/test-session';
import JiraTrivialIcon from '../glyph/jira/trivial';
import LabelIcon from '../glyph/label';
import LightbulbFilledIcon from '../glyph/lightbulb-filled';
import LightbulbIcon from '../glyph/lightbulb';
import LikeIcon from '../glyph/like';
import LinkFilledIcon from '../glyph/link-filled';
import LinkIcon from '../glyph/link';
import ListIcon from '../glyph/list';
import LocationIcon from '../glyph/location';
import LockCircleIcon from '../glyph/lock-circle';
import LockFilledIcon from '../glyph/lock-filled';
import LockIcon from '../glyph/lock';
import MarketplaceIcon from '../glyph/marketplace';
import MediaServicesActualSizeIcon from '../glyph/media-services/actual-size';
import MediaServicesAddCommentIcon from '../glyph/media-services/add-comment';
import MediaServicesAnnotateIcon from '../glyph/media-services/annotate';
import MediaServicesArrowIcon from '../glyph/media-services/arrow';
import MediaServicesAudioIcon from '../glyph/media-services/audio';
import MediaServicesBlurIcon from '../glyph/media-services/blur';
import MediaServicesBrushIcon from '../glyph/media-services/brush';
import MediaServicesButtonOptionIcon from '../glyph/media-services/button-option';
import MediaServicesCodeIcon from '../glyph/media-services/code';
import MediaServicesDocumentIcon from '../glyph/media-services/document';
import MediaServicesFilterIcon from '../glyph/media-services/filter';
import MediaServicesFitToPageIcon from '../glyph/media-services/fit-to-page';
import MediaServicesFullScreenIcon from '../glyph/media-services/full-screen';
import MediaServicesGridIcon from '../glyph/media-services/grid';
import MediaServicesImageIcon from '../glyph/media-services/image';
import MediaServicesLineThicknessIcon from '../glyph/media-services/line-thickness';
import MediaServicesLineIcon from '../glyph/media-services/line';
import MediaServicesNoImageIcon from '../glyph/media-services/no-image';
import MediaServicesOpenMediaviewerIcon from '../glyph/media-services/open-mediaviewer';
import MediaServicesOvalIcon from '../glyph/media-services/oval';
import MediaServicesPdfIcon from '../glyph/media-services/pdf';
import MediaServicesPreselectedIcon from '../glyph/media-services/preselected';
import MediaServicesPresentationIcon from '../glyph/media-services/presentation';
import MediaServicesRectangleIcon from '../glyph/media-services/rectangle';
import MediaServicesScaleLargeIcon from '../glyph/media-services/scale-large';
import MediaServicesScaleSmallIcon from '../glyph/media-services/scale-small';
import MediaServicesSpreadsheetIcon from '../glyph/media-services/spreadsheet';
import MediaServicesTextIcon from '../glyph/media-services/text';
import MediaServicesUnknownIcon from '../glyph/media-services/unknown';
import MediaServicesVideoIcon from '../glyph/media-services/video';
import MediaServicesZipIcon from '../glyph/media-services/zip';
import MediaServicesZoomInIcon from '../glyph/media-services/zoom-in';
import MediaServicesZoomOutIcon from '../glyph/media-services/zoom-out';
import MentionIcon from '../glyph/mention';
import MenuIcon from '../glyph/menu';
import MoreVerticalIcon from '../glyph/more-vertical';
import MoreIcon from '../glyph/more';
import NotificationAllIcon from '../glyph/notification-all';
import NotificationDirectIcon from '../glyph/notification-direct';
import NotificationIcon from '../glyph/notification';
import OfficeBuildingFilledIcon from '../glyph/office-building-filled';
import OfficeBuildingIcon from '../glyph/office-building';
import OpenIcon from '../glyph/open';
import OverviewIcon from '../glyph/overview';
import PageFilledIcon from '../glyph/page-filled';
import PageIcon from '../glyph/page';
import PdfIcon from '../glyph/pdf';
import PeopleGroupIcon from '../glyph/people-group';
import PeopleIcon from '../glyph/people';
import PersonCircleIcon from '../glyph/person-circle';
import PersonIcon from '../glyph/person';
import PortfolioIcon from '../glyph/portfolio';
import PreferencesIcon from '../glyph/preferences';
import PresenceActiveIcon from '../glyph/presence-active';
import PresenceBusyIcon from '../glyph/presence-busy';
import PresenceUnavailableIcon from '../glyph/presence-unavailable';
import QuestionCircleIcon from '../glyph/question-circle';
import QuestionIcon from '../glyph/question';
import QuestionsIcon from '../glyph/questions';
import QueuesIcon from '../glyph/queues';
import QuoteIcon from '../glyph/quote';
import RadioIcon from '../glyph/radio';
import RecentIcon from '../glyph/recent';
import RedoIcon from '../glyph/redo';
import RefreshIcon from '../glyph/refresh';
import RoadmapIcon from '../glyph/roadmap';
import RoomMenuIcon from '../glyph/room-menu';
import ScheduleFilledIcon from '../glyph/schedule-filled';
import ScheduleIcon from '../glyph/schedule';
import ScreenIcon from '../glyph/screen';
import SearchIcon from '../glyph/search';
import SelectClearIcon from '../glyph/select-clear';
import SendIcon from '../glyph/send';
import SettingsIcon from '../glyph/settings';
import ShareIcon from '../glyph/share';
import ShipIcon from '../glyph/ship';
import ShortcutIcon from '../glyph/shortcut';
import SignInIcon from '../glyph/sign-in';
import SignOutIcon from '../glyph/sign-out';
import StarFilledIcon from '../glyph/star-filled';
import StarLargeIcon from '../glyph/star-large';
import StarOutlineIcon from '../glyph/star-outline';
import StarIcon from '../glyph/star';
import SubtaskIcon from '../glyph/subtask';
import SuitcaseIcon from '../glyph/suitcase';
import SwitcherIcon from '../glyph/switcher';
import TableIcon from '../glyph/table';
import TaskIcon from '../glyph/task';
import TrashIcon from '../glyph/trash';
import TrayIcon from '../glyph/tray';
import UndoIcon from '../glyph/undo';
import UnlinkIcon from '../glyph/unlink';
import UnlockCircleIcon from '../glyph/unlock-circle';
import UnlockFilledIcon from '../glyph/unlock-filled';
import UnlockIcon from '../glyph/unlock';
import UploadIcon from '../glyph/upload';
import UserAvatarCircleIcon from '../glyph/user-avatar-circle';
import VidAudioMutedIcon from '../glyph/vid-audio-muted';
import VidAudioOnIcon from '../glyph/vid-audio-on';
import VidBackwardIcon from '../glyph/vid-backward';
import VidCameraOffIcon from '../glyph/vid-camera-off';
import VidCameraOnIcon from '../glyph/vid-camera-on';
import VidConnectionCircleIcon from '../glyph/vid-connection-circle';
import VidForwardIcon from '../glyph/vid-forward';
import VidFullScreenOffIcon from '../glyph/vid-full-screen-off';
import VidFullScreenOnIcon from '../glyph/vid-full-screen-on';
import VidHangUpIcon from '../glyph/vid-hang-up';
import VidHdCircleIcon from '../glyph/vid-hd-circle';
import VidPauseIcon from '../glyph/vid-pause';
import VidPlayIcon from '../glyph/vid-play';
import VidRaisedHandIcon from '../glyph/vid-raised-hand';
import VidShareScreenIcon from '../glyph/vid-share-screen';
import VidSpeakingCircleIcon from '../glyph/vid-speaking-circle';
import VidVolumeFullIcon from '../glyph/vid-volume-full';
import VidVolumeHalfIcon from '../glyph/vid-volume-half';
import VidVolumeMutedIcon from '../glyph/vid-volume-muted';
import VideoCircleIcon from '../glyph/video-circle';
import VideoFilledIcon from '../glyph/video-filled';
import WarningIcon from '../glyph/warning';
import WatchFilledIcon from '../glyph/watch-filled';
import WatchIcon from '../glyph/watch';
import WorldSmallIcon from '../glyph/world-small';
import WorldIcon from '../glyph/world';

export default {
  activity: {
    keywords: ['activity', 'window', 'icon', 'core'],
    component: ActivityIcon,
    componentName: 'ActivityIcon',
    package: '@atlaskit/icon/glyph/activity',
  },
  'add-circle': {
    keywords: ['add-circle', 'addcircle', 'plus', 'create', 'new', 'icon', 'core'],
    component: AddCircleIcon,
    componentName: 'AddCircleIcon',
    package: '@atlaskit/icon/glyph/add-circle',
  },
  'add-item': {
    keywords: ['add-item', 'additem', 'plus', 'create', 'new', 'icon', 'core'],
    component: AddItemIcon,
    componentName: 'AddItemIcon',
    package: '@atlaskit/icon/glyph/add-item',
  },
  add: {
    keywords: ['add', 'plus', 'create', 'new', 'icon', 'core'],
    component: AddIcon,
    componentName: 'AddIcon',
    package: '@atlaskit/icon/glyph/add',
  },
  addon: {
    keywords: ['addon', 'icon', 'core'],
    component: AddonIcon,
    componentName: 'AddonIcon',
    package: '@atlaskit/icon/glyph/addon',
  },
  'app-access': {
    keywords: ['app-access', 'appaccess', 'icon', 'core'],
    component: AppAccessIcon,
    componentName: 'AppAccessIcon',
    package: '@atlaskit/icon/glyph/app-access',
  },
  'app-switcher': {
    keywords: ['app-switcher', 'appswitcher', 'icon', 'core'],
    component: AppSwitcherIcon,
    componentName: 'AppSwitcherIcon',
    package: '@atlaskit/icon/glyph/app-switcher',
  },
  'arrow-down-circle': {
    keywords: ['arrow-down-circle', 'arrowdowncircle', 'icon', 'core'],
    component: ArrowDownCircleIcon,
    componentName: 'ArrowDownCircleIcon',
    package: '@atlaskit/icon/glyph/arrow-down-circle',
  },
  'arrow-down': {
    keywords: ['arrow-down', 'arrowdown', 'icon', 'core'],
    component: ArrowDownIcon,
    componentName: 'ArrowDownIcon',
    package: '@atlaskit/icon/glyph/arrow-down',
  },
  'arrow-left-circle': {
    keywords: ['arrow-left-circle', 'arrowleftcircle', 'back', 'previous', 'icon', 'core'],
    component: ArrowLeftCircleIcon,
    componentName: 'ArrowLeftCircleIcon',
    package: '@atlaskit/icon/glyph/arrow-left-circle',
  },
  'arrow-left': {
    keywords: ['arrow-left', 'arrowleft', 'back', 'previous', 'icon', 'core'],
    component: ArrowLeftIcon,
    componentName: 'ArrowLeftIcon',
    package: '@atlaskit/icon/glyph/arrow-left',
  },
  'arrow-right-circle': {
    keywords: ['arrow-right-circle', 'arrowrightcircle', 'forward', 'next', 'icon', 'core'],
    component: ArrowRightCircleIcon,
    componentName: 'ArrowRightCircleIcon',
    package: '@atlaskit/icon/glyph/arrow-right-circle',
  },
  'arrow-right': {
    keywords: ['arrow-right', 'arrowright', 'forward', 'next', 'icon', 'core'],
    component: ArrowRightIcon,
    componentName: 'ArrowRightIcon',
    package: '@atlaskit/icon/glyph/arrow-right',
  },
  'arrow-up-circle': {
    keywords: ['arrow-up-circle', 'arrowupcircle', 'icon', 'core'],
    component: ArrowUpCircleIcon,
    componentName: 'ArrowUpCircleIcon',
    package: '@atlaskit/icon/glyph/arrow-up-circle',
  },
  'arrow-up': {
    keywords: ['arrow-up', 'arrowup', 'icon', 'core'],
    component: ArrowUpIcon,
    componentName: 'ArrowUpIcon',
    package: '@atlaskit/icon/glyph/arrow-up',
  },
  attachment: {
    keywords: ['attachment', 'paperclip', 'icon', 'core'],
    component: AttachmentIcon,
    componentName: 'AttachmentIcon',
    package: '@atlaskit/icon/glyph/attachment',
  },
  'audio-circle': {
    keywords: ['audio-circle', 'audiocircle', 'music', 'note', 'sound', 'icon', 'core'],
    component: AudioCircleIcon,
    componentName: 'AudioCircleIcon',
    package: '@atlaskit/icon/glyph/audio-circle',
  },
  audio: {
    keywords: ['audio', 'music', 'note', 'sound', 'icon', 'core'],
    component: AudioIcon,
    componentName: 'AudioIcon',
    package: '@atlaskit/icon/glyph/audio',
  },
  backlog: {
    keywords: ['backlog', 'icon', 'core'],
    component: BacklogIcon,
    componentName: 'BacklogIcon',
    package: '@atlaskit/icon/glyph/backlog',
  },
  'billing-filled': {
    keywords: ['billing-filled', 'billingfilled', 'icon', 'core'],
    component: BillingFilledIcon,
    componentName: 'BillingFilledIcon',
    package: '@atlaskit/icon/glyph/billing-filled',
  },
  billing: {
    keywords: ['billing', 'invoice', 'receipt', 'icon', 'core'],
    component: BillingIcon,
    componentName: 'BillingIcon',
    package: '@atlaskit/icon/glyph/billing',
  },
  'bitbucket/branches': {
    keywords: ['bitbucket/branches', 'bitbucketbranches', 'icon', 'core'],
    component: BitbucketBranchesIcon,
    componentName: 'BitbucketBranchesIcon',
    package: '@atlaskit/icon/glyph/bitbucket/branches',
  },
  'bitbucket/builds': {
    keywords: ['bitbucket/builds', 'bitbucketbuilds', 'icon', 'core'],
    component: BitbucketBuildsIcon,
    componentName: 'BitbucketBuildsIcon',
    package: '@atlaskit/icon/glyph/bitbucket/builds',
  },
  'bitbucket/clone': {
    keywords: ['bitbucket/clone', 'bitbucketclone', 'icon', 'core'],
    component: BitbucketCloneIcon,
    componentName: 'BitbucketCloneIcon',
    package: '@atlaskit/icon/glyph/bitbucket/clone',
  },
  'bitbucket/commits': {
    keywords: ['bitbucket/commits', 'bitbucketcommits', 'icon', 'core'],
    component: BitbucketCommitsIcon,
    componentName: 'BitbucketCommitsIcon',
    package: '@atlaskit/icon/glyph/bitbucket/commits',
  },
  'bitbucket/compare': {
    keywords: ['bitbucket/compare', 'bitbucketcompare', 'icon', 'core'],
    component: BitbucketCompareIcon,
    componentName: 'BitbucketCompareIcon',
    package: '@atlaskit/icon/glyph/bitbucket/compare',
  },
  'bitbucket/forks': {
    keywords: ['bitbucket/forks', 'bitbucketforks', 'icon', 'core'],
    component: BitbucketForksIcon,
    componentName: 'BitbucketForksIcon',
    package: '@atlaskit/icon/glyph/bitbucket/forks',
  },
  'bitbucket/output': {
    keywords: ['bitbucket/output', 'bitbucketoutput', 'icon', 'core'],
    component: BitbucketOutputIcon,
    componentName: 'BitbucketOutputIcon',
    package: '@atlaskit/icon/glyph/bitbucket/output',
  },
  'bitbucket/pipelines': {
    keywords: ['bitbucket/pipelines', 'bitbucketpipelines', 'icon', 'core'],
    component: BitbucketPipelinesIcon,
    componentName: 'BitbucketPipelinesIcon',
    package: '@atlaskit/icon/glyph/bitbucket/pipelines',
  },
  'bitbucket/pullrequests': {
    keywords: ['bitbucket/pullrequests', 'bitbucketpullrequests', 'icon', 'core'],
    component: BitbucketPullrequestsIcon,
    componentName: 'BitbucketPullrequestsIcon',
    package: '@atlaskit/icon/glyph/bitbucket/pullrequests',
  },
  'bitbucket/repos': {
    keywords: ['bitbucket/repos', 'bitbucketrepos', 'icon', 'core'],
    component: BitbucketReposIcon,
    componentName: 'BitbucketReposIcon',
    package: '@atlaskit/icon/glyph/bitbucket/repos',
  },
  'bitbucket/snippets': {
    keywords: ['bitbucket/snippets', 'bitbucketsnippets', 'scissors', 'icon', 'core'],
    component: BitbucketSnippetsIcon,
    componentName: 'BitbucketSnippetsIcon',
    package: '@atlaskit/icon/glyph/bitbucket/snippets',
  },
  'bitbucket/source': {
    keywords: ['bitbucket/source', 'bitbucketsource', 'code', 'icon', 'core'],
    component: BitbucketSourceIcon,
    componentName: 'BitbucketSourceIcon',
    package: '@atlaskit/icon/glyph/bitbucket/source',
  },
  board: {
    keywords: ['board', 'icon', 'core'],
    component: BoardIcon,
    componentName: 'BoardIcon',
    package: '@atlaskit/icon/glyph/board',
  },
  book: {
    keywords: ['book', 'icon', 'core'],
    component: BookIcon,
    componentName: 'BookIcon',
    package: '@atlaskit/icon/glyph/book',
  },
  'bullet-list': {
    keywords: ['bullet-list', 'bulletlist', 'ul', 'icon', 'core'],
    component: BulletListIcon,
    componentName: 'BulletListIcon',
    package: '@atlaskit/icon/glyph/bullet-list',
  },
  'calendar-filled': {
    keywords: ['calendar-filled', 'calendarfilled', 'date', 'icon', 'core'],
    component: CalendarFilledIcon,
    componentName: 'CalendarFilledIcon',
    package: '@atlaskit/icon/glyph/calendar-filled',
  },
  calendar: {
    keywords: ['calendar', 'date', 'icon', 'core'],
    component: CalendarIcon,
    componentName: 'CalendarIcon',
    package: '@atlaskit/icon/glyph/calendar',
  },
  'camera-filled': {
    keywords: ['camera-filled', 'camerafilled', 'photo', 'icon', 'core'],
    component: CameraFilledIcon,
    componentName: 'CameraFilledIcon',
    package: '@atlaskit/icon/glyph/camera-filled',
  },
  'camera-rotate': {
    keywords: ['camera-rotate', 'camerarotate', 'photo', 'icon', 'core'],
    component: CameraRotateIcon,
    componentName: 'CameraRotateIcon',
    package: '@atlaskit/icon/glyph/camera-rotate',
  },
  'camera-take-picture': {
    keywords: ['camera-take-picture', 'cameratakepicture', 'photo', 'icon', 'core'],
    component: CameraTakePictureIcon,
    componentName: 'CameraTakePictureIcon',
    package: '@atlaskit/icon/glyph/camera-take-picture',
  },
  camera: {
    keywords: ['camera', 'photo', 'icon', 'core'],
    component: CameraIcon,
    componentName: 'CameraIcon',
    package: '@atlaskit/icon/glyph/camera',
  },
  canvas: {
    keywords: ['canvas', 'easel', 'icon', 'core'],
    component: CanvasIcon,
    componentName: 'CanvasIcon',
    package: '@atlaskit/icon/glyph/canvas',
  },
  'check-circle-outline': {
    keywords: ['check-circle-outline', 'checkcircleoutline', 'icon', 'core'],
    component: CheckCircleOutlineIcon,
    componentName: 'CheckCircleOutlineIcon',
    package: '@atlaskit/icon/glyph/check-circle-outline',
  },
  'check-circle': {
    keywords: ['check-circle', 'checkcircle', 'tick', 'icon', 'core'],
    component: CheckCircleIcon,
    componentName: 'CheckCircleIcon',
    package: '@atlaskit/icon/glyph/check-circle',
  },
  check: {
    keywords: ['check', 'tick', 'confirm', 'icon', 'core'],
    component: CheckIcon,
    componentName: 'CheckIcon',
    package: '@atlaskit/icon/glyph/check',
  },
  'checkbox-indeterminate': {
    keywords: ['checkbox-indeterminate', 'checkboxindeterminate', 'icon', 'core'],
    component: CheckboxIndeterminateIcon,
    componentName: 'CheckboxIndeterminateIcon',
    package: '@atlaskit/icon/glyph/checkbox-indeterminate',
  },
  checkbox: {
    keywords: ['checkbox', 'tick', 'icon', 'core'],
    component: CheckboxIcon,
    componentName: 'CheckboxIcon',
    package: '@atlaskit/icon/glyph/checkbox',
  },
  'chevron-down-circle': {
    keywords: ['chevron-down-circle', 'chevrondowncircle', 'expand', 'collapse', 'icon', 'core'],
    component: ChevronDownCircleIcon,
    componentName: 'ChevronDownCircleIcon',
    package: '@atlaskit/icon/glyph/chevron-down-circle',
  },
  'chevron-down': {
    keywords: ['chevron-down', 'chevrondown', 'expand', 'collapse', 'icon', 'core'],
    component: ChevronDownIcon,
    componentName: 'ChevronDownIcon',
    package: '@atlaskit/icon/glyph/chevron-down',
  },
  'chevron-left-circle': {
    keywords: ['chevron-left-circle', 'chevronleftcircle', 'back', 'previous', 'icon', 'core'],
    component: ChevronLeftCircleIcon,
    componentName: 'ChevronLeftCircleIcon',
    package: '@atlaskit/icon/glyph/chevron-left-circle',
  },
  'chevron-left-large': {
    keywords: ['chevron-left-large', 'chevronleftlarge', 'icon', 'core'],
    component: ChevronLeftLargeIcon,
    componentName: 'ChevronLeftLargeIcon',
    package: '@atlaskit/icon/glyph/chevron-left-large',
  },
  'chevron-left': {
    keywords: ['chevron-left', 'chevronleft', 'back', 'previous', 'icon', 'core'],
    component: ChevronLeftIcon,
    componentName: 'ChevronLeftIcon',
    package: '@atlaskit/icon/glyph/chevron-left',
  },
  'chevron-right-circle': {
    keywords: ['chevron-right-circle', 'chevronrightcircle', 'forward', 'next', 'icon', 'core'],
    component: ChevronRightCircleIcon,
    componentName: 'ChevronRightCircleIcon',
    package: '@atlaskit/icon/glyph/chevron-right-circle',
  },
  'chevron-right-large': {
    keywords: ['chevron-right-large', 'chevronrightlarge', 'icon', 'core'],
    component: ChevronRightLargeIcon,
    componentName: 'ChevronRightLargeIcon',
    package: '@atlaskit/icon/glyph/chevron-right-large',
  },
  'chevron-right': {
    keywords: ['chevron-right', 'chevronright', 'forward', 'next', 'icon', 'core'],
    component: ChevronRightIcon,
    componentName: 'ChevronRightIcon',
    package: '@atlaskit/icon/glyph/chevron-right',
  },
  'chevron-up-circle': {
    keywords: ['chevron-up-circle', 'chevronupcircle', 'expand', 'collapse', 'icon', 'core'],
    component: ChevronUpCircleIcon,
    componentName: 'ChevronUpCircleIcon',
    package: '@atlaskit/icon/glyph/chevron-up-circle',
  },
  'chevron-up': {
    keywords: ['chevron-up', 'chevronup', 'expand', 'collapse', 'icon', 'core'],
    component: ChevronUpIcon,
    componentName: 'ChevronUpIcon',
    package: '@atlaskit/icon/glyph/chevron-up',
  },
  'child-issues': {
    keywords: ['child-issues', 'childissues', 'icon', 'core'],
    component: ChildIssuesIcon,
    componentName: 'ChildIssuesIcon',
    package: '@atlaskit/icon/glyph/child-issues',
  },
  code: {
    keywords: ['code', 'source', 'icon', 'core'],
    component: CodeIcon,
    componentName: 'CodeIcon',
    package: '@atlaskit/icon/glyph/code',
  },
  comment: {
    keywords: ['comment', 'chat', 'speech', 'icon', 'core'],
    component: CommentIcon,
    componentName: 'CommentIcon',
    package: '@atlaskit/icon/glyph/comment',
  },
  component: {
    keywords: ['component', 'block', 'lego', 'icon', 'core'],
    component: ComponentIcon,
    componentName: 'ComponentIcon',
    package: '@atlaskit/icon/glyph/component',
  },
  copy: {
    keywords: ['copy', 'duplicate', 'icon', 'core'],
    component: CopyIcon,
    componentName: 'CopyIcon',
    package: '@atlaskit/icon/glyph/copy',
  },
  'creditcard-filled': {
    keywords: ['creditcard-filled', 'creditcardfilled', 'buy', 'pay', 'purchase', 'icon', 'core'],
    component: CreditcardFilledIcon,
    componentName: 'CreditcardFilledIcon',
    package: '@atlaskit/icon/glyph/creditcard-filled',
  },
  creditcard: {
    keywords: ['creditcard', 'buy', 'pay', 'purchase', 'icon', 'core'],
    component: CreditcardIcon,
    componentName: 'CreditcardIcon',
    package: '@atlaskit/icon/glyph/creditcard',
  },
  'cross-circle': {
    keywords: ['cross-circle', 'crosscircle', 'close', 'x', 'cancel', 'icon', 'core'],
    component: CrossCircleIcon,
    componentName: 'CrossCircleIcon',
    package: '@atlaskit/icon/glyph/cross-circle',
  },
  cross: {
    keywords: ['cross', 'close', 'x', 'cancel', 'icon', 'core'],
    component: CrossIcon,
    componentName: 'CrossIcon',
    package: '@atlaskit/icon/glyph/cross',
  },
  dashboard: {
    keywords: ['dashboard', 'window', 'grid', 'icon', 'core'],
    component: DashboardIcon,
    componentName: 'DashboardIcon',
    package: '@atlaskit/icon/glyph/dashboard',
  },
  decision: {
    keywords: ['decision', 'icon', 'core'],
    component: DecisionIcon,
    componentName: 'DecisionIcon',
    package: '@atlaskit/icon/glyph/decision',
  },
  department: {
    keywords: ['department', 'icon', 'core'],
    component: DepartmentIcon,
    componentName: 'DepartmentIcon',
    package: '@atlaskit/icon/glyph/department',
  },
  'detail-view': {
    keywords: ['detail-view', 'detailview', 'icon', 'core'],
    component: DetailViewIcon,
    componentName: 'DetailViewIcon',
    package: '@atlaskit/icon/glyph/detail-view',
  },
  'discover-filled': {
    keywords: ['discover-filled', 'discoverfilled', 'compass', 'navigate', 'icon', 'core'],
    component: DiscoverFilledIcon,
    componentName: 'DiscoverFilledIcon',
    package: '@atlaskit/icon/glyph/discover-filled',
  },
  discover: {
    keywords: ['discover', 'compass', 'navigate', 'icon', 'core'],
    component: DiscoverIcon,
    componentName: 'DiscoverIcon',
    package: '@atlaskit/icon/glyph/discover',
  },
  'document-filled': {
    keywords: ['document-filled', 'documentfilled', 'page', 'paper', 'sheet', 'file', 'icon', 'core'],
    component: DocumentFilledIcon,
    componentName: 'DocumentFilledIcon',
    package: '@atlaskit/icon/glyph/document-filled',
  },
  document: {
    keywords: ['document', 'page', 'paper', 'sheet', 'file', 'icon', 'core'],
    component: DocumentIcon,
    componentName: 'DocumentIcon',
    package: '@atlaskit/icon/glyph/document',
  },
  documents: {
    keywords: ['documents', 'page', 'paper', 'sheet', 'file', 'icon', 'core'],
    component: DocumentsIcon,
    componentName: 'DocumentsIcon',
    package: '@atlaskit/icon/glyph/documents',
  },
  download: {
    keywords: ['download', 'cloud', 'icon', 'core'],
    component: DownloadIcon,
    componentName: 'DownloadIcon',
    package: '@atlaskit/icon/glyph/download',
  },
  'drag-handler': {
    keywords: ['drag-handler', 'draghandler', 'icon', 'core'],
    component: DragHandlerIcon,
    componentName: 'DragHandlerIcon',
    package: '@atlaskit/icon/glyph/drag-handler',
  },
  dropbox: {
    keywords: ['dropbox', 'icon', 'core'],
    component: DropboxIcon,
    componentName: 'DropboxIcon',
    package: '@atlaskit/icon/glyph/dropbox',
  },
  'edit-filled': {
    keywords: ['edit-filled', 'editfilled', 'pencil', 'write', 'icon', 'core'],
    component: EditFilledIcon,
    componentName: 'EditFilledIcon',
    package: '@atlaskit/icon/glyph/edit-filled',
  },
  edit: {
    keywords: ['edit', 'pencil', 'write', 'icon', 'core'],
    component: EditIcon,
    componentName: 'EditIcon',
    package: '@atlaskit/icon/glyph/edit',
  },
  'editor/add': {
    keywords: ['editor/add', 'editoradd', 'plus', 'create', 'new', 'icon', 'core'],
    component: EditorAddIcon,
    componentName: 'EditorAddIcon',
    package: '@atlaskit/icon/glyph/editor/add',
  },
  'editor/addon': {
    keywords: ['editor/addon', 'editoraddon', 'jigsaw', 'icon', 'core'],
    component: EditorAddonIcon,
    componentName: 'EditorAddonIcon',
    package: '@atlaskit/icon/glyph/editor/addon',
  },
  'editor/advanced': {
    keywords: ['editor/advanced', 'editoradvanced', 'strikethrough', 'type', 'font', 'typography', 'icon', 'core'],
    component: EditorAdvancedIcon,
    componentName: 'EditorAdvancedIcon',
    package: '@atlaskit/icon/glyph/editor/advanced',
  },
  'editor/align-center': {
    keywords: ['editor/align-center', 'editoraligncenter', 'icon', 'core'],
    component: EditorAlignCenterIcon,
    componentName: 'EditorAlignCenterIcon',
    package: '@atlaskit/icon/glyph/editor/align-center',
  },
  'editor/align-image-center': {
    keywords: ['editor/align-image-center', 'editoralignimagecenter', 'icon', 'core'],
    component: EditorAlignImageCenterIcon,
    componentName: 'EditorAlignImageCenterIcon',
    package: '@atlaskit/icon/glyph/editor/align-image-center',
  },
  'editor/align-image-left': {
    keywords: ['editor/align-image-left', 'editoralignimageleft', 'icon', 'core'],
    component: EditorAlignImageLeftIcon,
    componentName: 'EditorAlignImageLeftIcon',
    package: '@atlaskit/icon/glyph/editor/align-image-left',
  },
  'editor/align-image-right': {
    keywords: ['editor/align-image-right', 'editoralignimageright', 'icon', 'core'],
    component: EditorAlignImageRightIcon,
    componentName: 'EditorAlignImageRightIcon',
    package: '@atlaskit/icon/glyph/editor/align-image-right',
  },
  'editor/align-left': {
    keywords: ['editor/align-left', 'editoralignleft', 'icon', 'core'],
    component: EditorAlignLeftIcon,
    componentName: 'EditorAlignLeftIcon',
    package: '@atlaskit/icon/glyph/editor/align-left',
  },
  'editor/align-right': {
    keywords: ['editor/align-right', 'editoralignright', 'icon', 'core'],
    component: EditorAlignRightIcon,
    componentName: 'EditorAlignRightIcon',
    package: '@atlaskit/icon/glyph/editor/align-right',
  },
  'editor/attachment': {
    keywords: ['editor/attachment', 'editorattachment', 'paperclip', 'icon', 'core'],
    component: EditorAttachmentIcon,
    componentName: 'EditorAttachmentIcon',
    package: '@atlaskit/icon/glyph/editor/attachment',
  },
  'editor/background-color': {
    keywords: ['editor/background-color', 'editorbackgroundcolor', 'fill', 'icon', 'core'],
    component: EditorBackgroundColorIcon,
    componentName: 'EditorBackgroundColorIcon',
    package: '@atlaskit/icon/glyph/editor/background-color',
  },
  'editor/bold': {
    keywords: ['editor/bold', 'editorbold', 'icon', 'core'],
    component: EditorBoldIcon,
    componentName: 'EditorBoldIcon',
    package: '@atlaskit/icon/glyph/editor/bold',
  },
  'editor/bullet-list': {
    keywords: ['editor/bullet-list', 'editorbulletlist', 'ul', 'icon', 'core'],
    component: EditorBulletListIcon,
    componentName: 'EditorBulletListIcon',
    package: '@atlaskit/icon/glyph/editor/bullet-list',
  },
  'editor/close': {
    keywords: ['editor/close', 'editorclose', 'x', 'cancel', 'cross', 'icon', 'core'],
    component: EditorCloseIcon,
    componentName: 'EditorCloseIcon',
    package: '@atlaskit/icon/glyph/editor/close',
  },
  'editor/code': {
    keywords: ['editor/code', 'editorcode', 'source', 'icon', 'core'],
    component: EditorCodeIcon,
    componentName: 'EditorCodeIcon',
    package: '@atlaskit/icon/glyph/editor/code',
  },
  'editor/collapse': {
    keywords: ['editor/collapse', 'editorcollapse', 'close', 'icon', 'core'],
    component: EditorCollapseIcon,
    componentName: 'EditorCollapseIcon',
    package: '@atlaskit/icon/glyph/editor/collapse',
  },
  'editor/date': {
    keywords: ['editor/date', 'editordate', 'calendar', 'icon', 'core'],
    component: EditorDateIcon,
    componentName: 'EditorDateIcon',
    package: '@atlaskit/icon/glyph/editor/date',
  },
  'editor/decision': {
    keywords: ['editor/decision', 'editordecision', 'icon', 'core'],
    component: EditorDecisionIcon,
    componentName: 'EditorDecisionIcon',
    package: '@atlaskit/icon/glyph/editor/decision',
  },
  'editor/divider': {
    keywords: ['editor/divider', 'editordivider', 'icon', 'core'],
    component: EditorDividerIcon,
    componentName: 'EditorDividerIcon',
    package: '@atlaskit/icon/glyph/editor/divider',
  },
  'editor/done': {
    keywords: ['editor/done', 'editordone', 'check', 'tick', 'icon', 'core'],
    component: EditorDoneIcon,
    componentName: 'EditorDoneIcon',
    package: '@atlaskit/icon/glyph/editor/done',
  },
  'editor/edit': {
    keywords: ['editor/edit', 'editoredit', 'pencil', 'write', 'icon', 'core'],
    component: EditorEditIcon,
    componentName: 'EditorEditIcon',
    package: '@atlaskit/icon/glyph/editor/edit',
  },
  'editor/emoji': {
    keywords: ['editor/emoji', 'editoremoji', 'emoticon', 'smiley', 'icon', 'core'],
    component: EditorEmojiIcon,
    componentName: 'EditorEmojiIcon',
    package: '@atlaskit/icon/glyph/editor/emoji',
  },
  'editor/error': {
    keywords: ['editor/error', 'editorerror', 'warning', 'alert', 'icon', 'core'],
    component: EditorErrorIcon,
    componentName: 'EditorErrorIcon',
    package: '@atlaskit/icon/glyph/editor/error',
  },
  'editor/expand': {
    keywords: ['editor/expand', 'editorexpand', 'open', 'icon', 'core'],
    component: EditorExpandIcon,
    componentName: 'EditorExpandIcon',
    package: '@atlaskit/icon/glyph/editor/expand',
  },
  'editor/feedback': {
    keywords: ['editor/feedback', 'editorfeedback', 'announce', 'speaker', 'megaphone', 'icon', 'core'],
    component: EditorFeedbackIcon,
    componentName: 'EditorFeedbackIcon',
    package: '@atlaskit/icon/glyph/editor/feedback',
  },
  'editor/file': {
    keywords: ['editor/file', 'editorfile', 'page', 'document', 'paper', 'sheet', 'icon', 'core'],
    component: EditorFileIcon,
    componentName: 'EditorFileIcon',
    package: '@atlaskit/icon/glyph/editor/file',
  },
  'editor/help': {
    keywords: ['editor/help', 'editorhelp', 'question', 'icon', 'core'],
    component: EditorHelpIcon,
    componentName: 'EditorHelpIcon',
    package: '@atlaskit/icon/glyph/editor/help',
  },
  'editor/hint': {
    keywords: ['editor/hint', 'editorhint', 'light', 'idea', 'icon', 'core'],
    component: EditorHintIcon,
    componentName: 'EditorHintIcon',
    package: '@atlaskit/icon/glyph/editor/hint',
  },
  'editor/horizontal-rule': {
    keywords: ['editor/horizontal-rule', 'editorhorizontalrule', 'rule', 'divider', 'icon', 'core'],
    component: EditorHorizontalRuleIcon,
    componentName: 'EditorHorizontalRuleIcon',
    package: '@atlaskit/icon/glyph/editor/horizontal-rule',
  },
  'editor/image-border': {
    keywords: ['editor/image-border', 'editorimageborder', 'marquee', 'box', 'icon', 'core'],
    component: EditorImageBorderIcon,
    componentName: 'EditorImageBorderIcon',
    package: '@atlaskit/icon/glyph/editor/image-border',
  },
  'editor/image-resize': {
    keywords: ['editor/image-resize', 'editorimageresize', 'expand', 'icon', 'core'],
    component: EditorImageResizeIcon,
    componentName: 'EditorImageResizeIcon',
    package: '@atlaskit/icon/glyph/editor/image-resize',
  },
  'editor/image': {
    keywords: ['editor/image', 'editorimage', 'photo', 'picture', 'icon', 'core'],
    component: EditorImageIcon,
    componentName: 'EditorImageIcon',
    package: '@atlaskit/icon/glyph/editor/image',
  },
  'editor/indent': {
    keywords: ['editor/indent', 'editorindent', 'tab', 'spacing', 'padding', 'icon', 'core'],
    component: EditorIndentIcon,
    componentName: 'EditorIndentIcon',
    package: '@atlaskit/icon/glyph/editor/indent',
  },
  'editor/info': {
    keywords: ['editor/info', 'editorinfo', 'icon', 'core'],
    component: EditorInfoIcon,
    componentName: 'EditorInfoIcon',
    package: '@atlaskit/icon/glyph/editor/info',
  },
  'editor/italic': {
    keywords: ['editor/italic', 'editoritalic', 'icon', 'core'],
    component: EditorItalicIcon,
    componentName: 'EditorItalicIcon',
    package: '@atlaskit/icon/glyph/editor/italic',
  },
  'editor/layout-three-equal': {
    keywords: ['editor/layout-three-equal', 'editorlayoutthreeequal', 'icon', 'core'],
    component: EditorLayoutThreeEqualIcon,
    componentName: 'EditorLayoutThreeEqualIcon',
    package: '@atlaskit/icon/glyph/editor/layout-three-equal',
  },
  'editor/layout-three-with-sidebars': {
    keywords: ['editor/layout-three-with-sidebars', 'editorlayoutthreewithsidebars', 'icon', 'core'],
    component: EditorLayoutThreeWithSidebarsIcon,
    componentName: 'EditorLayoutThreeWithSidebarsIcon',
    package: '@atlaskit/icon/glyph/editor/layout-three-with-sidebars',
  },
  'editor/layout-two-equal': {
    keywords: ['editor/layout-two-equal', 'editorlayouttwoequal', 'icon', 'core'],
    component: EditorLayoutTwoEqualIcon,
    componentName: 'EditorLayoutTwoEqualIcon',
    package: '@atlaskit/icon/glyph/editor/layout-two-equal',
  },
  'editor/layout-two-left-sidebar': {
    keywords: ['editor/layout-two-left-sidebar', 'editorlayouttwoleftsidebar', 'icon', 'core'],
    component: EditorLayoutTwoLeftSidebarIcon,
    componentName: 'EditorLayoutTwoLeftSidebarIcon',
    package: '@atlaskit/icon/glyph/editor/layout-two-left-sidebar',
  },
  'editor/layout-two-right-sidebar': {
    keywords: ['editor/layout-two-right-sidebar', 'editorlayouttworightsidebar', 'icon', 'core'],
    component: EditorLayoutTwoRightSidebarIcon,
    componentName: 'EditorLayoutTwoRightSidebarIcon',
    package: '@atlaskit/icon/glyph/editor/layout-two-right-sidebar',
  },
  'editor/link': {
    keywords: ['editor/link', 'editorlink', 'icon', 'core'],
    component: EditorLinkIcon,
    componentName: 'EditorLinkIcon',
    package: '@atlaskit/icon/glyph/editor/link',
  },
  'editor/media-center': {
    keywords: ['editor/media-center', 'editormediacenter', 'layout', 'align', 'position', 'icon', 'core'],
    component: EditorMediaCenterIcon,
    componentName: 'EditorMediaCenterIcon',
    package: '@atlaskit/icon/glyph/editor/media-center',
  },
  'editor/media-full-width': {
    keywords: ['editor/media-full-width', 'editormediafullwidth', 'layout', 'align', 'position', 'icon', 'core'],
    component: EditorMediaFullWidthIcon,
    componentName: 'EditorMediaFullWidthIcon',
    package: '@atlaskit/icon/glyph/editor/media-full-width',
  },
  'editor/media-wide': {
    keywords: ['editor/media-wide', 'editormediawide', 'layout', 'align', 'position', 'icon', 'core'],
    component: EditorMediaWideIcon,
    componentName: 'EditorMediaWideIcon',
    package: '@atlaskit/icon/glyph/editor/media-wide',
  },
  'editor/media-wrap-left': {
    keywords: ['editor/media-wrap-left', 'editormediawrapleft', 'layout', 'align', 'position', 'icon', 'core'],
    component: EditorMediaWrapLeftIcon,
    componentName: 'EditorMediaWrapLeftIcon',
    package: '@atlaskit/icon/glyph/editor/media-wrap-left',
  },
  'editor/media-wrap-right': {
    keywords: ['editor/media-wrap-right', 'editormediawrapright', 'layout', 'align', 'position', 'icon', 'core'],
    component: EditorMediaWrapRightIcon,
    componentName: 'EditorMediaWrapRightIcon',
    package: '@atlaskit/icon/glyph/editor/media-wrap-right',
  },
  'editor/mention': {
    keywords: ['editor/mention', 'editormention', '@', 'person', 'user', 'icon', 'core'],
    component: EditorMentionIcon,
    componentName: 'EditorMentionIcon',
    package: '@atlaskit/icon/glyph/editor/mention',
  },
  'editor/more': {
    keywords: ['editor/more', 'editormore', 'dots', 'ellipses', 'icon', 'core'],
    component: EditorMoreIcon,
    componentName: 'EditorMoreIcon',
    package: '@atlaskit/icon/glyph/editor/more',
  },
  'editor/note': {
    keywords: ['editor/note', 'editornote', 'document', 'page', 'icon', 'core'],
    component: EditorNoteIcon,
    componentName: 'EditorNoteIcon',
    package: '@atlaskit/icon/glyph/editor/note',
  },
  'editor/number-list': {
    keywords: ['editor/number-list', 'editornumberlist', 'ol', 'icon', 'core'],
    component: EditorNumberListIcon,
    componentName: 'EditorNumberListIcon',
    package: '@atlaskit/icon/glyph/editor/number-list',
  },
  'editor/open': {
    keywords: ['editor/open', 'editoropen', 'icon', 'core'],
    component: EditorOpenIcon,
    componentName: 'EditorOpenIcon',
    package: '@atlaskit/icon/glyph/editor/open',
  },
  'editor/outdent': {
    keywords: ['editor/outdent', 'editoroutdent', 'indent', 'tab', 'spacing', 'padding', 'icon', 'core'],
    component: EditorOutdentIcon,
    componentName: 'EditorOutdentIcon',
    package: '@atlaskit/icon/glyph/editor/outdent',
  },
  'editor/panel': {
    keywords: ['editor/panel', 'editorpanel', 'info', 'icon', 'core'],
    component: EditorPanelIcon,
    componentName: 'EditorPanelIcon',
    package: '@atlaskit/icon/glyph/editor/panel',
  },
  'editor/photo': {
    keywords: ['editor/photo', 'editorphoto', 'camera', 'icon', 'core'],
    component: EditorPhotoIcon,
    componentName: 'EditorPhotoIcon',
    package: '@atlaskit/icon/glyph/editor/photo',
  },
  'editor/quote': {
    keywords: ['editor/quote', 'editorquote', 'icon', 'core'],
    component: EditorQuoteIcon,
    componentName: 'EditorQuoteIcon',
    package: '@atlaskit/icon/glyph/editor/quote',
  },
  'editor/recent': {
    keywords: ['editor/recent', 'editorrecent', 'clock', 'time', 'icon', 'core'],
    component: EditorRecentIcon,
    componentName: 'EditorRecentIcon',
    package: '@atlaskit/icon/glyph/editor/recent',
  },
  'editor/redo': {
    keywords: ['editor/redo', 'editorredo', 'icon', 'core'],
    component: EditorRedoIcon,
    componentName: 'EditorRedoIcon',
    package: '@atlaskit/icon/glyph/editor/redo',
  },
  'editor/remove': {
    keywords: ['editor/remove', 'editorremove', 'bin', 'trash', 'recycle', 'delete', 'icon', 'core'],
    component: EditorRemoveIcon,
    componentName: 'EditorRemoveIcon',
    package: '@atlaskit/icon/glyph/editor/remove',
  },
  'editor/search': {
    keywords: ['editor/search', 'editorsearch', 'magnifying', 'glass', 'find', 'icon', 'core'],
    component: EditorSearchIcon,
    componentName: 'EditorSearchIcon',
    package: '@atlaskit/icon/glyph/editor/search',
  },
  'editor/settings': {
    keywords: ['editor/settings', 'editorsettings', 'options', 'configuration', 'icon', 'core'],
    component: EditorSettingsIcon,
    componentName: 'EditorSettingsIcon',
    package: '@atlaskit/icon/glyph/editor/settings',
  },
  'editor/strikethrough': {
    keywords: ['editor/strikethrough', 'editorstrikethrough', 'strikethrough', 'type', 'font', 'typography', 'icon', 'core'],
    component: EditorStrikethroughIcon,
    componentName: 'EditorStrikethroughIcon',
    package: '@atlaskit/icon/glyph/editor/strikethrough',
  },
  'editor/success': {
    keywords: ['editor/success', 'editorsuccess', 'luck', 'achievement', 'icon', 'core'],
    component: EditorSuccessIcon,
    componentName: 'EditorSuccessIcon',
    package: '@atlaskit/icon/glyph/editor/success',
  },
  'editor/table-display-options': {
    keywords: ['editor/table-display-options', 'editortabledisplayoptions', 'display-options', 'display', 'icon', 'core'],
    component: EditorTableDisplayOptionsIcon,
    componentName: 'EditorTableDisplayOptionsIcon',
    package: '@atlaskit/icon/glyph/editor/table-display-options',
  },
  'editor/table': {
    keywords: ['editor/table', 'editortable', 'grid', 'icon', 'core'],
    component: EditorTableIcon,
    componentName: 'EditorTableIcon',
    package: '@atlaskit/icon/glyph/editor/table',
  },
  'editor/task': {
    keywords: ['editor/task', 'editortask', 'checkbox', 'tick', 'icon', 'core'],
    component: EditorTaskIcon,
    componentName: 'EditorTaskIcon',
    package: '@atlaskit/icon/glyph/editor/task',
  },
  'editor/text-color': {
    keywords: ['editor/text-color', 'editortextcolor', 'font', 'icon', 'core'],
    component: EditorTextColorIcon,
    componentName: 'EditorTextColorIcon',
    package: '@atlaskit/icon/glyph/editor/text-color',
  },
  'editor/text-style': {
    keywords: ['editor/text-style', 'editortextstyle', 'type', 'font', 'typography', 'icon', 'core'],
    component: EditorTextStyleIcon,
    componentName: 'EditorTextStyleIcon',
    package: '@atlaskit/icon/glyph/editor/text-style',
  },
  'editor/underline': {
    keywords: ['editor/underline', 'editorunderline', 'font', 'text', 'icon', 'core'],
    component: EditorUnderlineIcon,
    componentName: 'EditorUnderlineIcon',
    package: '@atlaskit/icon/glyph/editor/underline',
  },
  'editor/undo': {
    keywords: ['editor/undo', 'editorundo', 'icon', 'core'],
    component: EditorUndoIcon,
    componentName: 'EditorUndoIcon',
    package: '@atlaskit/icon/glyph/editor/undo',
  },
  'editor/unlink': {
    keywords: ['editor/unlink', 'editorunlink', 'icon', 'core'],
    component: EditorUnlinkIcon,
    componentName: 'EditorUnlinkIcon',
    package: '@atlaskit/icon/glyph/editor/unlink',
  },
  'editor/warning': {
    keywords: ['editor/warning', 'editorwarning', 'alert', 'error', 'icon', 'core'],
    component: EditorWarningIcon,
    componentName: 'EditorWarningIcon',
    package: '@atlaskit/icon/glyph/editor/warning',
  },
  email: {
    keywords: ['email', 'icon', 'core'],
    component: EmailIcon,
    componentName: 'EmailIcon',
    package: '@atlaskit/icon/glyph/email',
  },
  'emoji-add': {
    keywords: ['emoji-add', 'emojiadd', 'icon', 'core'],
    component: EmojiAddIcon,
    componentName: 'EmojiAddIcon',
    package: '@atlaskit/icon/glyph/emoji-add',
  },
  emoji: {
    keywords: ['emoji', 'emoticon', 'smiley', 'icon', 'core'],
    component: EmojiIcon,
    componentName: 'EmojiIcon',
    package: '@atlaskit/icon/glyph/emoji',
  },
  'emoji/activity': {
    keywords: ['emoji/activity', 'emojiactivity', 'tennis', 'ball', 'icon', 'core'],
    component: EmojiActivityIcon,
    componentName: 'EmojiActivityIcon',
    package: '@atlaskit/icon/glyph/emoji/activity',
  },
  'emoji/atlassian': {
    keywords: ['emoji/atlassian', 'emojiatlassian', 'icon', 'core'],
    component: EmojiAtlassianIcon,
    componentName: 'EmojiAtlassianIcon',
    package: '@atlaskit/icon/glyph/emoji/atlassian',
  },
  'emoji/custom': {
    keywords: ['emoji/custom', 'emojicustom', 'plus', 'add', 'create', 'new', 'icon', 'core'],
    component: EmojiCustomIcon,
    componentName: 'EmojiCustomIcon',
    package: '@atlaskit/icon/glyph/emoji/custom',
  },
  'emoji/emoji': {
    keywords: ['emoji/emoji', 'emojiemoji', 'emoticon', 'smiley', 'icon', 'core'],
    component: EmojiEmojiIcon,
    componentName: 'EmojiEmojiIcon',
    package: '@atlaskit/icon/glyph/emoji/emoji',
  },
  'emoji/flags': {
    keywords: ['emoji/flags', 'emojiflags', 'icon', 'core'],
    component: EmojiFlagsIcon,
    componentName: 'EmojiFlagsIcon',
    package: '@atlaskit/icon/glyph/emoji/flags',
  },
  'emoji/food': {
    keywords: ['emoji/food', 'emojifood', 'icon', 'core'],
    component: EmojiFoodIcon,
    componentName: 'EmojiFoodIcon',
    package: '@atlaskit/icon/glyph/emoji/food',
  },
  'emoji/frequent': {
    keywords: ['emoji/frequent', 'emojifrequent', 'time', 'clock', 'icon', 'core'],
    component: EmojiFrequentIcon,
    componentName: 'EmojiFrequentIcon',
    package: '@atlaskit/icon/glyph/emoji/frequent',
  },
  'emoji/keyboard': {
    keywords: ['emoji/keyboard', 'emojikeyboard', 'type', 'icon', 'core'],
    component: EmojiKeyboardIcon,
    componentName: 'EmojiKeyboardIcon',
    package: '@atlaskit/icon/glyph/emoji/keyboard',
  },
  'emoji/nature': {
    keywords: ['emoji/nature', 'emojinature', 'tree', 'icon', 'core'],
    component: EmojiNatureIcon,
    componentName: 'EmojiNatureIcon',
    package: '@atlaskit/icon/glyph/emoji/nature',
  },
  'emoji/objects': {
    keywords: ['emoji/objects', 'emojiobjects', 'light', 'icon', 'core'],
    component: EmojiObjectsIcon,
    componentName: 'EmojiObjectsIcon',
    package: '@atlaskit/icon/glyph/emoji/objects',
  },
  'emoji/people': {
    keywords: ['emoji/people', 'emojipeople', 'smiley', 'face', 'icon', 'core'],
    component: EmojiPeopleIcon,
    componentName: 'EmojiPeopleIcon',
    package: '@atlaskit/icon/glyph/emoji/people',
  },
  'emoji/productivity': {
    keywords: ['emoji/productivity', 'emojiproductivity', 'icon', 'core'],
    component: EmojiProductivityIcon,
    componentName: 'EmojiProductivityIcon',
    package: '@atlaskit/icon/glyph/emoji/productivity',
  },
  'emoji/symbols': {
    keywords: ['emoji/symbols', 'emojisymbols', 'heart', 'love', 'icon', 'core'],
    component: EmojiSymbolsIcon,
    componentName: 'EmojiSymbolsIcon',
    package: '@atlaskit/icon/glyph/emoji/symbols',
  },
  'emoji/travel': {
    keywords: ['emoji/travel', 'emojitravel', 'train', 'transport', 'icon', 'core'],
    component: EmojiTravelIcon,
    componentName: 'EmojiTravelIcon',
    package: '@atlaskit/icon/glyph/emoji/travel',
  },
  error: {
    keywords: ['error', 'warning', 'alert', 'icon', 'core'],
    component: ErrorIcon,
    componentName: 'ErrorIcon',
    package: '@atlaskit/icon/glyph/error',
  },
  export: {
    keywords: ['export', 'upload', 'icon', 'core'],
    component: ExportIcon,
    componentName: 'ExportIcon',
    package: '@atlaskit/icon/glyph/export',
  },
  feedback: {
    keywords: ['feedback', 'announce', 'speaker', 'megaphone', 'icon', 'core'],
    component: FeedbackIcon,
    componentName: 'FeedbackIcon',
    package: '@atlaskit/icon/glyph/feedback',
  },
  file: {
    keywords: ['file', 'document', 'paper', 'page', 'sheet', 'icon', 'core'],
    component: FileIcon,
    componentName: 'FileIcon',
    package: '@atlaskit/icon/glyph/file',
  },
  filter: {
    keywords: ['filter', 'icon', 'core'],
    component: FilterIcon,
    componentName: 'FilterIcon',
    package: '@atlaskit/icon/glyph/filter',
  },
  'flag-filled': {
    keywords: ['flag-filled', 'flagfilled', 'icon', 'core'],
    component: FlagFilledIcon,
    componentName: 'FlagFilledIcon',
    package: '@atlaskit/icon/glyph/flag-filled',
  },
  'folder-filled': {
    keywords: ['folder-filled', 'folderfilled', 'directory', 'icon', 'core'],
    component: FolderFilledIcon,
    componentName: 'FolderFilledIcon',
    package: '@atlaskit/icon/glyph/folder-filled',
  },
  folder: {
    keywords: ['folder', 'directory', 'icon', 'core'],
    component: FolderIcon,
    componentName: 'FolderIcon',
    package: '@atlaskit/icon/glyph/folder',
  },
  followers: {
    keywords: ['followers', 'person', 'user', 'icon', 'core'],
    component: FollowersIcon,
    componentName: 'FollowersIcon',
    package: '@atlaskit/icon/glyph/followers',
  },
  following: {
    keywords: ['following', 'person', 'user', 'icon', 'core'],
    component: FollowingIcon,
    componentName: 'FollowingIcon',
    package: '@atlaskit/icon/glyph/following',
  },
  googledrive: {
    keywords: ['googledrive', 'icon', 'core'],
    component: GoogledriveIcon,
    componentName: 'GoogledriveIcon',
    package: '@atlaskit/icon/glyph/googledrive',
  },
  'graph-bar': {
    keywords: ['graph-bar', 'graphbar', 'chart', 'growth', 'data', 'statistics', 'analytics', 'icon', 'core'],
    component: GraphBarIcon,
    componentName: 'GraphBarIcon',
    package: '@atlaskit/icon/glyph/graph-bar',
  },
  'graph-line': {
    keywords: ['graph-line', 'graphline', 'chart', 'growth', 'data', 'statistics', 'analytics', 'icon', 'core'],
    component: GraphLineIcon,
    componentName: 'GraphLineIcon',
    package: '@atlaskit/icon/glyph/graph-line',
  },
  gsuite: {
    keywords: ['gsuite', 'icon', 'core'],
    component: GsuiteIcon,
    componentName: 'GsuiteIcon',
    package: '@atlaskit/icon/glyph/gsuite',
  },
  highlights: {
    keywords: ['highlights', 'icon', 'core'],
    component: HighlightsIcon,
    componentName: 'HighlightsIcon',
    package: '@atlaskit/icon/glyph/highlights',
  },
  'hipchat/audio-only': {
    keywords: ['hipchat/audio-only', 'hipchataudioonly', 'audio', 'icon', 'core'],
    component: HipchatAudioOnlyIcon,
    componentName: 'HipchatAudioOnlyIcon',
    package: '@atlaskit/icon/glyph/hipchat/audio-only',
  },
  'hipchat/chevron-double-down': {
    keywords: ['hipchat/chevron-double-down', 'hipchatchevrondoubledown', 'icon', 'core'],
    component: HipchatChevronDoubleDownIcon,
    componentName: 'HipchatChevronDoubleDownIcon',
    package: '@atlaskit/icon/glyph/hipchat/chevron-double-down',
  },
  'hipchat/chevron-double-up': {
    keywords: ['hipchat/chevron-double-up', 'hipchatchevrondoubleup', 'icon', 'core'],
    component: HipchatChevronDoubleUpIcon,
    componentName: 'HipchatChevronDoubleUpIcon',
    package: '@atlaskit/icon/glyph/hipchat/chevron-double-up',
  },
  'hipchat/chevron-down': {
    keywords: ['hipchat/chevron-down', 'hipchatchevrondown', 'icon', 'core'],
    component: HipchatChevronDownIcon,
    componentName: 'HipchatChevronDownIcon',
    package: '@atlaskit/icon/glyph/hipchat/chevron-down',
  },
  'hipchat/chevron-up': {
    keywords: ['hipchat/chevron-up', 'hipchatchevronup', 'icon', 'core'],
    component: HipchatChevronUpIcon,
    componentName: 'HipchatChevronUpIcon',
    package: '@atlaskit/icon/glyph/hipchat/chevron-up',
  },
  'hipchat/dial-out': {
    keywords: ['hipchat/dial-out', 'hipchatdialout', 'dial', 'call', 'icon', 'core'],
    component: HipchatDialOutIcon,
    componentName: 'HipchatDialOutIcon',
    package: '@atlaskit/icon/glyph/hipchat/dial-out',
  },
  'hipchat/lobby': {
    keywords: ['hipchat/lobby', 'hipchatlobby', 'bell', 'icon', 'core'],
    component: HipchatLobbyIcon,
    componentName: 'HipchatLobbyIcon',
    package: '@atlaskit/icon/glyph/hipchat/lobby',
  },
  'hipchat/media-attachment-count': {
    keywords: ['hipchat/media-attachment-count', 'hipchatmediaattachmentcount', 'dot', 'icon', 'core'],
    component: HipchatMediaAttachmentCountIcon,
    componentName: 'HipchatMediaAttachmentCountIcon',
    package: '@atlaskit/icon/glyph/hipchat/media-attachment-count',
  },
  'hipchat/outgoing-sound': {
    keywords: ['hipchat/outgoing-sound', 'hipchatoutgoingsound', 'sound', 'icon', 'core'],
    component: HipchatOutgoingSoundIcon,
    componentName: 'HipchatOutgoingSoundIcon',
    package: '@atlaskit/icon/glyph/hipchat/outgoing-sound',
  },
  'hipchat/sd-video': {
    keywords: ['hipchat/sd-video', 'hipchatsdvideo', 'video', 'definition', 'icon', 'core'],
    component: HipchatSdVideoIcon,
    componentName: 'HipchatSdVideoIcon',
    package: '@atlaskit/icon/glyph/hipchat/sd-video',
  },
  'home-circle': {
    keywords: ['home-circle', 'homecircle', 'icon', 'core'],
    component: HomeCircleIcon,
    componentName: 'HomeCircleIcon',
    package: '@atlaskit/icon/glyph/home-circle',
  },
  'home-filled': {
    keywords: ['home-filled', 'homefilled', 'icon', 'core'],
    component: HomeFilledIcon,
    componentName: 'HomeFilledIcon',
    package: '@atlaskit/icon/glyph/home-filled',
  },
  'image-border': {
    keywords: ['image-border', 'imageborder', 'marquee', 'box', 'icon', 'core'],
    component: ImageBorderIcon,
    componentName: 'ImageBorderIcon',
    package: '@atlaskit/icon/glyph/image-border',
  },
  'image-resize': {
    keywords: ['image-resize', 'imageresize', 'expand', 'icon', 'core'],
    component: ImageResizeIcon,
    componentName: 'ImageResizeIcon',
    package: '@atlaskit/icon/glyph/image-resize',
  },
  image: {
    keywords: ['image', 'picture', 'photo', 'icon', 'core'],
    component: ImageIcon,
    componentName: 'ImageIcon',
    package: '@atlaskit/icon/glyph/image',
  },
  info: {
    keywords: ['info', 'icon', 'core'],
    component: InfoIcon,
    componentName: 'InfoIcon',
    package: '@atlaskit/icon/glyph/info',
  },
  'invite-team': {
    keywords: ['invite-team', 'inviteteam', 'add', 'person', 'user', 'icon', 'core'],
    component: InviteTeamIcon,
    componentName: 'InviteTeamIcon',
    package: '@atlaskit/icon/glyph/invite-team',
  },
  'issue-raise': {
    keywords: ['issue-raise', 'issueraise', 'add', 'create', 'plus', 'new', 'icon', 'core'],
    component: IssueRaiseIcon,
    componentName: 'IssueRaiseIcon',
    package: '@atlaskit/icon/glyph/issue-raise',
  },
  issue: {
    keywords: ['issue', 'tick', 'check', 'confirm', 'task', 'icon', 'core'],
    component: IssueIcon,
    componentName: 'IssueIcon',
    package: '@atlaskit/icon/glyph/issue',
  },
  issues: {
    keywords: ['issues', 'tick', 'check', 'confirm', 'task', 'icon', 'core'],
    component: IssuesIcon,
    componentName: 'IssuesIcon',
    package: '@atlaskit/icon/glyph/issues',
  },
  'jira/blocker': {
    keywords: ['jira/blocker', 'jirablocker', 'priority', 'issue', 'icon', 'core'],
    component: JiraBlockerIcon,
    componentName: 'JiraBlockerIcon',
    package: '@atlaskit/icon/glyph/jira/blocker',
  },
  'jira/capture': {
    keywords: ['jira/capture', 'jiracapture', 'icon', 'core'],
    component: JiraCaptureIcon,
    componentName: 'JiraCaptureIcon',
    package: '@atlaskit/icon/glyph/jira/capture',
  },
  'jira/critical': {
    keywords: ['jira/critical', 'jiracritical', 'priority', 'issue', 'icon', 'core'],
    component: JiraCriticalIcon,
    componentName: 'JiraCriticalIcon',
    package: '@atlaskit/icon/glyph/jira/critical',
  },
  'jira/failed-build-status': {
    keywords: ['jira/failed-build-status', 'jirafailedbuildstatus', 'icon', 'core'],
    component: JiraFailedBuildStatusIcon,
    componentName: 'JiraFailedBuildStatusIcon',
    package: '@atlaskit/icon/glyph/jira/failed-build-status',
  },
  'jira/labs': {
    keywords: ['jira/labs', 'jiralabs', 'icon', 'core'],
    component: JiraLabsIcon,
    componentName: 'JiraLabsIcon',
    package: '@atlaskit/icon/glyph/jira/labs',
  },
  'jira/major': {
    keywords: ['jira/major', 'jiramajor', 'priority', 'issue', 'icon', 'core'],
    component: JiraMajorIcon,
    componentName: 'JiraMajorIcon',
    package: '@atlaskit/icon/glyph/jira/major',
  },
  'jira/medium': {
    keywords: ['jira/medium', 'jiramedium', 'priority', 'issue', 'icon', 'core'],
    component: JiraMediumIcon,
    componentName: 'JiraMediumIcon',
    package: '@atlaskit/icon/glyph/jira/medium',
  },
  'jira/minor': {
    keywords: ['jira/minor', 'jiraminor', 'priority', 'issue', 'icon', 'core'],
    component: JiraMinorIcon,
    componentName: 'JiraMinorIcon',
    package: '@atlaskit/icon/glyph/jira/minor',
  },
  'jira/test-session': {
    keywords: ['jira/test-session', 'jiratestsession', 'icon', 'core'],
    component: JiraTestSessionIcon,
    componentName: 'JiraTestSessionIcon',
    package: '@atlaskit/icon/glyph/jira/test-session',
  },
  'jira/trivial': {
    keywords: ['jira/trivial', 'jiratrivial', 'priority', 'issue', 'icon', 'core'],
    component: JiraTrivialIcon,
    componentName: 'JiraTrivialIcon',
    package: '@atlaskit/icon/glyph/jira/trivial',
  },
  label: {
    keywords: ['label', 'icon', 'core'],
    component: LabelIcon,
    componentName: 'LabelIcon',
    package: '@atlaskit/icon/glyph/label',
  },
  'lightbulb-filled': {
    keywords: ['lightbulb-filled', 'lightbulbfilled', 'idea', 'hint', 'icon', 'core'],
    component: LightbulbFilledIcon,
    componentName: 'LightbulbFilledIcon',
    package: '@atlaskit/icon/glyph/lightbulb-filled',
  },
  lightbulb: {
    keywords: ['lightbulb', 'idea', 'hint', 'icon', 'core'],
    component: LightbulbIcon,
    componentName: 'LightbulbIcon',
    package: '@atlaskit/icon/glyph/lightbulb',
  },
  like: {
    keywords: ['like', 'icon', 'core'],
    component: LikeIcon,
    componentName: 'LikeIcon',
    package: '@atlaskit/icon/glyph/like',
  },
  'link-filled': {
    keywords: ['link-filled', 'linkfilled', 'icon', 'core'],
    component: LinkFilledIcon,
    componentName: 'LinkFilledIcon',
    package: '@atlaskit/icon/glyph/link-filled',
  },
  link: {
    keywords: ['link', 'icon', 'core'],
    component: LinkIcon,
    componentName: 'LinkIcon',
    package: '@atlaskit/icon/glyph/link',
  },
  list: {
    keywords: ['list', 'justify', 'ul', 'icon', 'core'],
    component: ListIcon,
    componentName: 'ListIcon',
    package: '@atlaskit/icon/glyph/list',
  },
  location: {
    keywords: ['location', 'pin', 'gps', 'map', 'icon', 'core'],
    component: LocationIcon,
    componentName: 'LocationIcon',
    package: '@atlaskit/icon/glyph/location',
  },
  'lock-circle': {
    keywords: ['lock-circle', 'lockcircle', 'closed', 'permissions', 'privacy', 'restrict', 'secure', 'icon', 'core'],
    component: LockCircleIcon,
    componentName: 'LockCircleIcon',
    package: '@atlaskit/icon/glyph/lock-circle',
  },
  'lock-filled': {
    keywords: ['lock-filled', 'lockfilled', 'closed', 'permissions', 'privacy', 'restrict', 'secure', 'icon', 'core'],
    component: LockFilledIcon,
    componentName: 'LockFilledIcon',
    package: '@atlaskit/icon/glyph/lock-filled',
  },
  lock: {
    keywords: ['lock', 'closed', 'permissions', 'privacy', 'restrict', 'secure', 'icon', 'core'],
    component: LockIcon,
    componentName: 'LockIcon',
    package: '@atlaskit/icon/glyph/lock',
  },
  marketplace: {
    keywords: ['marketplace', 'store', 'shop', 'icon', 'core'],
    component: MarketplaceIcon,
    componentName: 'MarketplaceIcon',
    package: '@atlaskit/icon/glyph/marketplace',
  },
  'media-services/actual-size': {
    keywords: ['media-services/actual-size', 'mediaservicesactualsize', 'icon', 'core'],
    component: MediaServicesActualSizeIcon,
    componentName: 'MediaServicesActualSizeIcon',
    package: '@atlaskit/icon/glyph/media-services/actual-size',
  },
  'media-services/add-comment': {
    keywords: ['media-services/add-comment', 'mediaservicesaddcomment', 'chat', 'new', 'create', 'icon', 'core'],
    component: MediaServicesAddCommentIcon,
    componentName: 'MediaServicesAddCommentIcon',
    package: '@atlaskit/icon/glyph/media-services/add-comment',
  },
  'media-services/annotate': {
    keywords: ['media-services/annotate', 'mediaservicesannotate', 'icon', 'core'],
    component: MediaServicesAnnotateIcon,
    componentName: 'MediaServicesAnnotateIcon',
    package: '@atlaskit/icon/glyph/media-services/annotate',
  },
  'media-services/arrow': {
    keywords: ['media-services/arrow', 'mediaservicesarrow', 'icon', 'core'],
    component: MediaServicesArrowIcon,
    componentName: 'MediaServicesArrowIcon',
    package: '@atlaskit/icon/glyph/media-services/arrow',
  },
  'media-services/audio': {
    keywords: ['media-services/audio', 'mediaservicesaudio', 'music', 'note', 'sound', 'icon', 'core'],
    component: MediaServicesAudioIcon,
    componentName: 'MediaServicesAudioIcon',
    package: '@atlaskit/icon/glyph/media-services/audio',
  },
  'media-services/blur': {
    keywords: ['media-services/blur', 'mediaservicesblur', 'pixelate', 'icon', 'core'],
    component: MediaServicesBlurIcon,
    componentName: 'MediaServicesBlurIcon',
    package: '@atlaskit/icon/glyph/media-services/blur',
  },
  'media-services/brush': {
    keywords: ['media-services/brush', 'mediaservicesbrush', 'paint', 'icon', 'core'],
    component: MediaServicesBrushIcon,
    componentName: 'MediaServicesBrushIcon',
    package: '@atlaskit/icon/glyph/media-services/brush',
  },
  'media-services/button-option': {
    keywords: ['media-services/button-option', 'mediaservicesbuttonoption', 'icon', 'core'],
    component: MediaServicesButtonOptionIcon,
    componentName: 'MediaServicesButtonOptionIcon',
    package: '@atlaskit/icon/glyph/media-services/button-option',
  },
  'media-services/code': {
    keywords: ['media-services/code', 'mediaservicescode', 'source', 'icon', 'core'],
    component: MediaServicesCodeIcon,
    componentName: 'MediaServicesCodeIcon',
    package: '@atlaskit/icon/glyph/media-services/code',
  },
  'media-services/document': {
    keywords: ['media-services/document', 'mediaservicesdocument', 'text', 'icon', 'core'],
    component: MediaServicesDocumentIcon,
    componentName: 'MediaServicesDocumentIcon',
    package: '@atlaskit/icon/glyph/media-services/document',
  },
  'media-services/filter': {
    keywords: ['media-services/filter', 'mediaservicesfilter', 'icon', 'core'],
    component: MediaServicesFilterIcon,
    componentName: 'MediaServicesFilterIcon',
    package: '@atlaskit/icon/glyph/media-services/filter',
  },
  'media-services/fit-to-page': {
    keywords: ['media-services/fit-to-page', 'mediaservicesfittopage', 'icon', 'core'],
    component: MediaServicesFitToPageIcon,
    componentName: 'MediaServicesFitToPageIcon',
    package: '@atlaskit/icon/glyph/media-services/fit-to-page',
  },
  'media-services/full-screen': {
    keywords: ['media-services/full-screen', 'mediaservicesfullscreen', 'icon', 'core'],
    component: MediaServicesFullScreenIcon,
    componentName: 'MediaServicesFullScreenIcon',
    package: '@atlaskit/icon/glyph/media-services/full-screen',
  },
  'media-services/grid': {
    keywords: ['media-services/grid', 'mediaservicesgrid', 'table', 'icon', 'core'],
    component: MediaServicesGridIcon,
    componentName: 'MediaServicesGridIcon',
    package: '@atlaskit/icon/glyph/media-services/grid',
  },
  'media-services/image': {
    keywords: ['media-services/image', 'mediaservicesimage', 'photo', 'picture', 'icon', 'core'],
    component: MediaServicesImageIcon,
    componentName: 'MediaServicesImageIcon',
    package: '@atlaskit/icon/glyph/media-services/image',
  },
  'media-services/line-thickness': {
    keywords: ['media-services/line-thickness', 'mediaserviceslinethickness', 'icon', 'core'],
    component: MediaServicesLineThicknessIcon,
    componentName: 'MediaServicesLineThicknessIcon',
    package: '@atlaskit/icon/glyph/media-services/line-thickness',
  },
  'media-services/line': {
    keywords: ['media-services/line', 'mediaservicesline', 'icon', 'core'],
    component: MediaServicesLineIcon,
    componentName: 'MediaServicesLineIcon',
    package: '@atlaskit/icon/glyph/media-services/line',
  },
  'media-services/no-image': {
    keywords: ['media-services/no-image', 'mediaservicesnoimage', 'icon', 'core'],
    component: MediaServicesNoImageIcon,
    componentName: 'MediaServicesNoImageIcon',
    package: '@atlaskit/icon/glyph/media-services/no-image',
  },
  'media-services/open-mediaviewer': {
    keywords: ['media-services/open-mediaviewer', 'mediaservicesopenmediaviewer', 'icon', 'core'],
    component: MediaServicesOpenMediaviewerIcon,
    componentName: 'MediaServicesOpenMediaviewerIcon',
    package: '@atlaskit/icon/glyph/media-services/open-mediaviewer',
  },
  'media-services/oval': {
    keywords: ['media-services/oval', 'mediaservicesoval', 'ellipse', 'icon', 'core'],
    component: MediaServicesOvalIcon,
    componentName: 'MediaServicesOvalIcon',
    package: '@atlaskit/icon/glyph/media-services/oval',
  },
  'media-services/pdf': {
    keywords: ['media-services/pdf', 'mediaservicespdf', 'document', 'icon', 'core'],
    component: MediaServicesPdfIcon,
    componentName: 'MediaServicesPdfIcon',
    package: '@atlaskit/icon/glyph/media-services/pdf',
  },
  'media-services/preselected': {
    keywords: ['media-services/preselected', 'mediaservicespreselected', 'circle', 'icon', 'core'],
    component: MediaServicesPreselectedIcon,
    componentName: 'MediaServicesPreselectedIcon',
    package: '@atlaskit/icon/glyph/media-services/preselected',
  },
  'media-services/presentation': {
    keywords: ['media-services/presentation', 'mediaservicespresentation', 'chart', 'graph', 'icon', 'core'],
    component: MediaServicesPresentationIcon,
    componentName: 'MediaServicesPresentationIcon',
    package: '@atlaskit/icon/glyph/media-services/presentation',
  },
  'media-services/rectangle': {
    keywords: ['media-services/rectangle', 'mediaservicesrectangle', 'box', 'icon', 'core'],
    component: MediaServicesRectangleIcon,
    componentName: 'MediaServicesRectangleIcon',
    package: '@atlaskit/icon/glyph/media-services/rectangle',
  },
  'media-services/scale-large': {
    keywords: ['media-services/scale-large', 'mediaservicesscalelarge', 'photo', 'picture', 'image', 'icon', 'core'],
    component: MediaServicesScaleLargeIcon,
    componentName: 'MediaServicesScaleLargeIcon',
    package: '@atlaskit/icon/glyph/media-services/scale-large',
  },
  'media-services/scale-small': {
    keywords: ['media-services/scale-small', 'mediaservicesscalesmall', 'photo', 'picture', 'image', 'icon', 'core'],
    component: MediaServicesScaleSmallIcon,
    componentName: 'MediaServicesScaleSmallIcon',
    package: '@atlaskit/icon/glyph/media-services/scale-small',
  },
  'media-services/spreadsheet': {
    keywords: ['media-services/spreadsheet', 'mediaservicesspreadsheet', 'document', 'excel', 'sheets', 'table', 'icon', 'core'],
    component: MediaServicesSpreadsheetIcon,
    componentName: 'MediaServicesSpreadsheetIcon',
    package: '@atlaskit/icon/glyph/media-services/spreadsheet',
  },
  'media-services/text': {
    keywords: ['media-services/text', 'mediaservicestext', 'type', 'typography', 'font', 'icon', 'core'],
    component: MediaServicesTextIcon,
    componentName: 'MediaServicesTextIcon',
    package: '@atlaskit/icon/glyph/media-services/text',
  },
  'media-services/unknown': {
    keywords: ['media-services/unknown', 'mediaservicesunknown', 'document', 'file', 'icon', 'core'],
    component: MediaServicesUnknownIcon,
    componentName: 'MediaServicesUnknownIcon',
    package: '@atlaskit/icon/glyph/media-services/unknown',
  },
  'media-services/video': {
    keywords: ['media-services/video', 'mediaservicesvideo', 'film', 'camera', 'icon', 'core'],
    component: MediaServicesVideoIcon,
    componentName: 'MediaServicesVideoIcon',
    package: '@atlaskit/icon/glyph/media-services/video',
  },
  'media-services/zip': {
    keywords: ['media-services/zip', 'mediaserviceszip', 'compress', 'icon', 'core'],
    component: MediaServicesZipIcon,
    componentName: 'MediaServicesZipIcon',
    package: '@atlaskit/icon/glyph/media-services/zip',
  },
  'media-services/zoom-in': {
    keywords: ['media-services/zoom-in', 'mediaserviceszoomin', 'magnify', 'icon', 'core'],
    component: MediaServicesZoomInIcon,
    componentName: 'MediaServicesZoomInIcon',
    package: '@atlaskit/icon/glyph/media-services/zoom-in',
  },
  'media-services/zoom-out': {
    keywords: ['media-services/zoom-out', 'mediaserviceszoomout', 'magnify', 'icon', 'core'],
    component: MediaServicesZoomOutIcon,
    componentName: 'MediaServicesZoomOutIcon',
    package: '@atlaskit/icon/glyph/media-services/zoom-out',
  },
  mention: {
    keywords: ['mention', 'user', 'person', '@', 'icon', 'core'],
    component: MentionIcon,
    componentName: 'MentionIcon',
    package: '@atlaskit/icon/glyph/mention',
  },
  menu: {
    keywords: ['menu', 'hamburger', 'navigation', 'switcher', 'app switcher', 'icon', 'core'],
    component: MenuIcon,
    componentName: 'MenuIcon',
    package: '@atlaskit/icon/glyph/menu',
  },
  'more-vertical': {
    keywords: ['more-vertical', 'morevertical', 'dots', 'icon', 'core'],
    component: MoreVerticalIcon,
    componentName: 'MoreVerticalIcon',
    package: '@atlaskit/icon/glyph/more-vertical',
  },
  more: {
    keywords: ['more', 'dots', 'ellipses', 'icon', 'core'],
    component: MoreIcon,
    componentName: 'MoreIcon',
    package: '@atlaskit/icon/glyph/more',
  },
  'notification-all': {
    keywords: ['notification-all', 'notificationall', 'bell', 'alarm', 'icon', 'core'],
    component: NotificationAllIcon,
    componentName: 'NotificationAllIcon',
    package: '@atlaskit/icon/glyph/notification-all',
  },
  'notification-direct': {
    keywords: ['notification-direct', 'notificationdirect', 'bell', 'alarm', 'icon', 'core'],
    component: NotificationDirectIcon,
    componentName: 'NotificationDirectIcon',
    package: '@atlaskit/icon/glyph/notification-direct',
  },
  notification: {
    keywords: ['notification', 'bell', 'alarm', 'icon', 'core'],
    component: NotificationIcon,
    componentName: 'NotificationIcon',
    package: '@atlaskit/icon/glyph/notification',
  },
  'office-building-filled': {
    keywords: ['office-building-filled', 'officebuildingfilled', 'icon', 'core'],
    component: OfficeBuildingFilledIcon,
    componentName: 'OfficeBuildingFilledIcon',
    package: '@atlaskit/icon/glyph/office-building-filled',
  },
  'office-building': {
    keywords: ['office-building', 'officebuilding', 'icon', 'core'],
    component: OfficeBuildingIcon,
    componentName: 'OfficeBuildingIcon',
    package: '@atlaskit/icon/glyph/office-building',
  },
  open: {
    keywords: ['open', 'icon', 'core'],
    component: OpenIcon,
    componentName: 'OpenIcon',
    package: '@atlaskit/icon/glyph/open',
  },
  overview: {
    keywords: ['overview', 'icon', 'core'],
    component: OverviewIcon,
    componentName: 'OverviewIcon',
    package: '@atlaskit/icon/glyph/overview',
  },
  'page-filled': {
    keywords: ['page-filled', 'pagefilled', 'file', 'document', 'icon', 'core'],
    component: PageFilledIcon,
    componentName: 'PageFilledIcon',
    package: '@atlaskit/icon/glyph/page-filled',
  },
  page: {
    keywords: ['page', 'file', 'document', 'icon', 'core'],
    component: PageIcon,
    componentName: 'PageIcon',
    package: '@atlaskit/icon/glyph/page',
  },
  pdf: {
    keywords: ['pdf', 'document', 'file', 'icon', 'core'],
    component: PdfIcon,
    componentName: 'PdfIcon',
    package: '@atlaskit/icon/glyph/pdf',
  },
  'people-group': {
    keywords: ['people-group', 'peoplegroup', 'person', 'user', 'group', 'icon', 'core'],
    component: PeopleGroupIcon,
    componentName: 'PeopleGroupIcon',
    package: '@atlaskit/icon/glyph/people-group',
  },
  people: {
    keywords: ['people', 'person', 'user', 'group', 'icon', 'core'],
    component: PeopleIcon,
    componentName: 'PeopleIcon',
    package: '@atlaskit/icon/glyph/people',
  },
  'person-circle': {
    keywords: ['person-circle', 'personcircle', 'icon', 'core'],
    component: PersonCircleIcon,
    componentName: 'PersonCircleIcon',
    package: '@atlaskit/icon/glyph/person-circle',
  },
  person: {
    keywords: ['person', 'person', 'user', 'avatar', 'icon', 'core'],
    component: PersonIcon,
    componentName: 'PersonIcon',
    package: '@atlaskit/icon/glyph/person',
  },
  portfolio: {
    keywords: ['portfolio', 'icon', 'core'],
    component: PortfolioIcon,
    componentName: 'PortfolioIcon',
    package: '@atlaskit/icon/glyph/portfolio',
  },
  preferences: {
    keywords: ['preferences', 'settings', 'configuration', 'options', 'icon', 'core'],
    component: PreferencesIcon,
    componentName: 'PreferencesIcon',
    package: '@atlaskit/icon/glyph/preferences',
  },
  'presence-active': {
    keywords: ['presence-active', 'presenceactive', 'dot', 'icon', 'core'],
    component: PresenceActiveIcon,
    componentName: 'PresenceActiveIcon',
    package: '@atlaskit/icon/glyph/presence-active',
  },
  'presence-busy': {
    keywords: ['presence-busy', 'presencebusy', 'block', 'do not disturb', 'icon', 'core'],
    component: PresenceBusyIcon,
    componentName: 'PresenceBusyIcon',
    package: '@atlaskit/icon/glyph/presence-busy',
  },
  'presence-unavailable': {
    keywords: ['presence-unavailable', 'presenceunavailable', 'icon', 'core'],
    component: PresenceUnavailableIcon,
    componentName: 'PresenceUnavailableIcon',
    package: '@atlaskit/icon/glyph/presence-unavailable',
  },
  'question-circle': {
    keywords: ['question-circle', 'questioncircle', 'help', 'icon', 'core'],
    component: QuestionCircleIcon,
    componentName: 'QuestionCircleIcon',
    package: '@atlaskit/icon/glyph/question-circle',
  },
  question: {
    keywords: ['question', 'help', 'icon', 'core'],
    component: QuestionIcon,
    componentName: 'QuestionIcon',
    package: '@atlaskit/icon/glyph/question',
  },
  questions: {
    keywords: ['questions', 'icon', 'core'],
    component: QuestionsIcon,
    componentName: 'QuestionsIcon',
    package: '@atlaskit/icon/glyph/questions',
  },
  queues: {
    keywords: ['queues', 'icon', 'core'],
    component: QueuesIcon,
    componentName: 'QueuesIcon',
    package: '@atlaskit/icon/glyph/queues',
  },
  quote: {
    keywords: ['quote', 'icon', 'core'],
    component: QuoteIcon,
    componentName: 'QuoteIcon',
    package: '@atlaskit/icon/glyph/quote',
  },
  radio: {
    keywords: ['radio', 'icon', 'core'],
    component: RadioIcon,
    componentName: 'RadioIcon',
    package: '@atlaskit/icon/glyph/radio',
  },
  recent: {
    keywords: ['recent', 'time', 'clock', 'icon', 'core'],
    component: RecentIcon,
    componentName: 'RecentIcon',
    package: '@atlaskit/icon/glyph/recent',
  },
  redo: {
    keywords: ['redo', 'icon', 'core'],
    component: RedoIcon,
    componentName: 'RedoIcon',
    package: '@atlaskit/icon/glyph/redo',
  },
  refresh: {
    keywords: ['refresh', 'cycle', 'icon', 'core'],
    component: RefreshIcon,
    componentName: 'RefreshIcon',
    package: '@atlaskit/icon/glyph/refresh',
  },
  roadmap: {
    keywords: ['roadmap', 'icon', 'core'],
    component: RoadmapIcon,
    componentName: 'RoadmapIcon',
    package: '@atlaskit/icon/glyph/roadmap',
  },
  'room-menu': {
    keywords: ['room-menu', 'roommenu', 'icon', 'core'],
    component: RoomMenuIcon,
    componentName: 'RoomMenuIcon',
    package: '@atlaskit/icon/glyph/room-menu',
  },
  'schedule-filled': {
    keywords: ['schedule-filled', 'schedulefilled', 'icon', 'core'],
    component: ScheduleFilledIcon,
    componentName: 'ScheduleFilledIcon',
    package: '@atlaskit/icon/glyph/schedule-filled',
  },
  schedule: {
    keywords: ['schedule', 'calendar', 'date', 'new', 'icon', 'core'],
    component: ScheduleIcon,
    componentName: 'ScheduleIcon',
    package: '@atlaskit/icon/glyph/schedule',
  },
  screen: {
    keywords: ['screen', 'desktop', 'computer', 'monitor', 'icon', 'core'],
    component: ScreenIcon,
    componentName: 'ScreenIcon',
    package: '@atlaskit/icon/glyph/screen',
  },
  search: {
    keywords: ['search', 'find', 'magnify', 'icon', 'core'],
    component: SearchIcon,
    componentName: 'SearchIcon',
    package: '@atlaskit/icon/glyph/search',
  },
  'select-clear': {
    keywords: ['select-clear', 'selectclear', 'icon', 'core'],
    component: SelectClearIcon,
    componentName: 'SelectClearIcon',
    package: '@atlaskit/icon/glyph/select-clear',
  },
  send: {
    keywords: ['send', 'mail', 'icon', 'core'],
    component: SendIcon,
    componentName: 'SendIcon',
    package: '@atlaskit/icon/glyph/send',
  },
  settings: {
    keywords: ['settings', 'cog', 'options', 'configuration', 'icon', 'core'],
    component: SettingsIcon,
    componentName: 'SettingsIcon',
    package: '@atlaskit/icon/glyph/settings',
  },
  share: {
    keywords: ['share', 'icon', 'core'],
    component: ShareIcon,
    componentName: 'ShareIcon',
    package: '@atlaskit/icon/glyph/share',
  },
  ship: {
    keywords: ['ship', 'icon', 'core'],
    component: ShipIcon,
    componentName: 'ShipIcon',
    package: '@atlaskit/icon/glyph/ship',
  },
  shortcut: {
    keywords: ['shortcut', 'export', 'icon', 'core'],
    component: ShortcutIcon,
    componentName: 'ShortcutIcon',
    package: '@atlaskit/icon/glyph/shortcut',
  },
  'sign-in': {
    keywords: ['sign-in', 'signin', 'log', 'icon', 'core'],
    component: SignInIcon,
    componentName: 'SignInIcon',
    package: '@atlaskit/icon/glyph/sign-in',
  },
  'sign-out': {
    keywords: ['sign-out', 'signout', 'log', 'icon', 'core'],
    component: SignOutIcon,
    componentName: 'SignOutIcon',
    package: '@atlaskit/icon/glyph/sign-out',
  },
  'star-filled': {
    keywords: ['star-filled', 'starfilled', 'icon', 'core'],
    component: StarFilledIcon,
    componentName: 'StarFilledIcon',
    package: '@atlaskit/icon/glyph/star-filled',
  },
  'star-large': {
    keywords: ['star-large', 'starlarge', 'icon', 'core'],
    component: StarLargeIcon,
    componentName: 'StarLargeIcon',
    package: '@atlaskit/icon/glyph/star-large',
  },
  'star-outline': {
    keywords: ['star-outline', 'staroutline', 'icon', 'core'],
    component: StarOutlineIcon,
    componentName: 'StarOutlineIcon',
    package: '@atlaskit/icon/glyph/star-outline',
  },
  star: {
    keywords: ['star', 'icon', 'core'],
    component: StarIcon,
    componentName: 'StarIcon',
    package: '@atlaskit/icon/glyph/star',
  },
  subtask: {
    keywords: ['subtask', 'issue', 'task', 'icon', 'core'],
    component: SubtaskIcon,
    componentName: 'SubtaskIcon',
    package: '@atlaskit/icon/glyph/subtask',
  },
  suitcase: {
    keywords: ['suitcase', 'icon', 'core'],
    component: SuitcaseIcon,
    componentName: 'SuitcaseIcon',
    package: '@atlaskit/icon/glyph/suitcase',
  },
  switcher: {
    keywords: ['switcher', 'icon', 'core'],
    component: SwitcherIcon,
    componentName: 'SwitcherIcon',
    package: '@atlaskit/icon/glyph/switcher',
  },
  table: {
    keywords: ['table', 'grid', 'icon', 'core'],
    component: TableIcon,
    componentName: 'TableIcon',
    package: '@atlaskit/icon/glyph/table',
  },
  task: {
    keywords: ['task', 'check', 'tick', 'icon', 'core'],
    component: TaskIcon,
    componentName: 'TaskIcon',
    package: '@atlaskit/icon/glyph/task',
  },
  trash: {
    keywords: ['trash', 'bin', 'remove', 'delete', 'recycle', 'icon', 'core'],
    component: TrashIcon,
    componentName: 'TrashIcon',
    package: '@atlaskit/icon/glyph/trash',
  },
  tray: {
    keywords: ['tray', 'inbox', 'icon', 'core'],
    component: TrayIcon,
    componentName: 'TrayIcon',
    package: '@atlaskit/icon/glyph/tray',
  },
  undo: {
    keywords: ['undo', 'icon', 'core'],
    component: UndoIcon,
    componentName: 'UndoIcon',
    package: '@atlaskit/icon/glyph/undo',
  },
  unlink: {
    keywords: ['unlink', 'icon', 'core'],
    component: UnlinkIcon,
    componentName: 'UnlinkIcon',
    package: '@atlaskit/icon/glyph/unlink',
  },
  'unlock-circle': {
    keywords: ['unlock-circle', 'unlockcircle', 'open', 'permissions', 'privacy', 'restrict', 'insecure', 'icon', 'core'],
    component: UnlockCircleIcon,
    componentName: 'UnlockCircleIcon',
    package: '@atlaskit/icon/glyph/unlock-circle',
  },
  'unlock-filled': {
    keywords: ['unlock-filled', 'unlockfilled', 'open', 'permissions', 'privacy', 'restrict', 'insecure', 'icon', 'core'],
    component: UnlockFilledIcon,
    componentName: 'UnlockFilledIcon',
    package: '@atlaskit/icon/glyph/unlock-filled',
  },
  unlock: {
    keywords: ['unlock', 'open', 'permissions', 'privacy', 'restrict', 'insecure', 'icon', 'core'],
    component: UnlockIcon,
    componentName: 'UnlockIcon',
    package: '@atlaskit/icon/glyph/unlock',
  },
  upload: {
    keywords: ['upload', 'cloud', 'icon', 'core'],
    component: UploadIcon,
    componentName: 'UploadIcon',
    package: '@atlaskit/icon/glyph/upload',
  },
  'user-avatar-circle': {
    keywords: ['user-avatar-circle', 'useravatarcircle', 'person', 'icon', 'core'],
    component: UserAvatarCircleIcon,
    componentName: 'UserAvatarCircleIcon',
    package: '@atlaskit/icon/glyph/user-avatar-circle',
  },
  'vid-audio-muted': {
    keywords: ['vid-audio-muted', 'vidaudiomuted', 'microphone', 'sound', 'icon', 'core'],
    component: VidAudioMutedIcon,
    componentName: 'VidAudioMutedIcon',
    package: '@atlaskit/icon/glyph/vid-audio-muted',
  },
  'vid-audio-on': {
    keywords: ['vid-audio-on', 'vidaudioon', 'microphone', 'sound', 'icon', 'core'],
    component: VidAudioOnIcon,
    componentName: 'VidAudioOnIcon',
    package: '@atlaskit/icon/glyph/vid-audio-on',
  },
  'vid-backward': {
    keywords: ['vid-backward', 'vidbackward', 'rewind', 'icon', 'core'],
    component: VidBackwardIcon,
    componentName: 'VidBackwardIcon',
    package: '@atlaskit/icon/glyph/vid-backward',
  },
  'vid-camera-off': {
    keywords: ['vid-camera-off', 'vidcameraoff', 'video', 'icon', 'core'],
    component: VidCameraOffIcon,
    componentName: 'VidCameraOffIcon',
    package: '@atlaskit/icon/glyph/vid-camera-off',
  },
  'vid-camera-on': {
    keywords: ['vid-camera-on', 'vidcameraon', 'icon', 'core'],
    component: VidCameraOnIcon,
    componentName: 'VidCameraOnIcon',
    package: '@atlaskit/icon/glyph/vid-camera-on',
  },
  'vid-connection-circle': {
    keywords: ['vid-connection-circle', 'vidconnectioncircle', 'signal', 'bar', 'icon', 'core'],
    component: VidConnectionCircleIcon,
    componentName: 'VidConnectionCircleIcon',
    package: '@atlaskit/icon/glyph/vid-connection-circle',
  },
  'vid-forward': {
    keywords: ['vid-forward', 'vidforward', 'fast', 'icon', 'core'],
    component: VidForwardIcon,
    componentName: 'VidForwardIcon',
    package: '@atlaskit/icon/glyph/vid-forward',
  },
  'vid-full-screen-off': {
    keywords: ['vid-full-screen-off', 'vidfullscreenoff', 'collapse', 'close', 'icon', 'core'],
    component: VidFullScreenOffIcon,
    componentName: 'VidFullScreenOffIcon',
    package: '@atlaskit/icon/glyph/vid-full-screen-off',
  },
  'vid-full-screen-on': {
    keywords: ['vid-full-screen-on', 'vidfullscreenon', 'expand', 'icon', 'core'],
    component: VidFullScreenOnIcon,
    componentName: 'VidFullScreenOnIcon',
    package: '@atlaskit/icon/glyph/vid-full-screen-on',
  },
  'vid-hang-up': {
    keywords: ['vid-hang-up', 'vidhangup', 'end', 'call', 'icon', 'core'],
    component: VidHangUpIcon,
    componentName: 'VidHangUpIcon',
    package: '@atlaskit/icon/glyph/vid-hang-up',
  },
  'vid-hd-circle': {
    keywords: ['vid-hd-circle', 'vidhdcircle', 'high', 'definition', 'icon', 'core'],
    component: VidHdCircleIcon,
    componentName: 'VidHdCircleIcon',
    package: '@atlaskit/icon/glyph/vid-hd-circle',
  },
  'vid-pause': {
    keywords: ['vid-pause', 'vidpause', 'icon', 'core'],
    component: VidPauseIcon,
    componentName: 'VidPauseIcon',
    package: '@atlaskit/icon/glyph/vid-pause',
  },
  'vid-play': {
    keywords: ['vid-play', 'vidplay', 'icon', 'core'],
    component: VidPlayIcon,
    componentName: 'VidPlayIcon',
    package: '@atlaskit/icon/glyph/vid-play',
  },
  'vid-raised-hand': {
    keywords: ['vid-raised-hand', 'vidraisedhand', 'person', 'question', 'user', 'arm', 'icon', 'core'],
    component: VidRaisedHandIcon,
    componentName: 'VidRaisedHandIcon',
    package: '@atlaskit/icon/glyph/vid-raised-hand',
  },
  'vid-share-screen': {
    keywords: ['vid-share-screen', 'vidsharescreen', 'icon', 'core'],
    component: VidShareScreenIcon,
    componentName: 'VidShareScreenIcon',
    package: '@atlaskit/icon/glyph/vid-share-screen',
  },
  'vid-speaking-circle': {
    keywords: ['vid-speaking-circle', 'vidspeakingcircle', 'sound', 'talk', 'audio', 'icon', 'core'],
    component: VidSpeakingCircleIcon,
    componentName: 'VidSpeakingCircleIcon',
    package: '@atlaskit/icon/glyph/vid-speaking-circle',
  },
  'vid-volume-full': {
    keywords: ['vid-volume-full', 'vidvolumefull', 'icon', 'core'],
    component: VidVolumeFullIcon,
    componentName: 'VidVolumeFullIcon',
    package: '@atlaskit/icon/glyph/vid-volume-full',
  },
  'vid-volume-half': {
    keywords: ['vid-volume-half', 'vidvolumehalf', 'icon', 'core'],
    component: VidVolumeHalfIcon,
    componentName: 'VidVolumeHalfIcon',
    package: '@atlaskit/icon/glyph/vid-volume-half',
  },
  'vid-volume-muted': {
    keywords: ['vid-volume-muted', 'vidvolumemuted', 'icon', 'core'],
    component: VidVolumeMutedIcon,
    componentName: 'VidVolumeMutedIcon',
    package: '@atlaskit/icon/glyph/vid-volume-muted',
  },
  'video-circle': {
    keywords: ['video-circle', 'videocircle', 'video', 'camera', 'icon', 'core'],
    component: VideoCircleIcon,
    componentName: 'VideoCircleIcon',
    package: '@atlaskit/icon/glyph/video-circle',
  },
  'video-filled': {
    keywords: ['video-filled', 'videofilled', 'video', 'camera', 'icon', 'core'],
    component: VideoFilledIcon,
    componentName: 'VideoFilledIcon',
    package: '@atlaskit/icon/glyph/video-filled',
  },
  warning: {
    keywords: ['warning', 'error', 'alert', 'icon', 'core'],
    component: WarningIcon,
    componentName: 'WarningIcon',
    package: '@atlaskit/icon/glyph/warning',
  },
  'watch-filled': {
    keywords: ['watch-filled', 'watchfilled', 'visible', 'visibility', 'eye', 'icon', 'core'],
    component: WatchFilledIcon,
    componentName: 'WatchFilledIcon',
    package: '@atlaskit/icon/glyph/watch-filled',
  },
  watch: {
    keywords: ['watch', 'visible', 'visibility', 'eye', 'icon', 'core'],
    component: WatchIcon,
    componentName: 'WatchIcon',
    package: '@atlaskit/icon/glyph/watch',
  },
  'world-small': {
    keywords: ['world-small', 'worldsmall', 'icon', 'core'],
    component: WorldSmallIcon,
    componentName: 'WorldSmallIcon',
    package: '@atlaskit/icon/glyph/world-small',
  },
  world: {
    keywords: ['world', 'globe', 'earth', 'icon', 'core'],
    component: WorldIcon,
    componentName: 'WorldIcon',
    package: '@atlaskit/icon/glyph/world',
  },
};
